# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
# Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
        cxxflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      modules:
      - clang/9.0.0
      operating_system: rhel7
      paths:
        cc: /usr/tce/packages/clang/clang-9.0.0/bin/clang
        cxx: /usr/tce/packages/clang/clang-9.0.0/bin/clang++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: clang@9.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
        cxxflags: --gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1
      modules:
      - clang/10.0.0
      operating_system: rhel7
      paths:
        cc: /usr/tce/packages/clang/clang-10.0.0/bin/clang
        cxx: /usr/tce/packages/clang/clang-10.0.0/bin/clang++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: clang@10.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel7
      paths:
        cc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gcc
        cxx: /usr/tce/packages/gcc/gcc-8.3.1/bin/g++
        f77: /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
        fc:  /usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran
      spec: gcc@8.3.1
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: rhel7
      paths:
        cc:  /usr/tce/packages/gcc/gcc-8.1.0/bin/gcc
        cxx: /usr/tce/packages/gcc/gcc-8.1.0/bin/g++
        f77:
        fc:
      # Note: Spack keeps having problems with specs with non-numerical compiler specs.
      # This is a special compiler spec to test out not defining a fortran compiler.
      spec: gcc@8.1.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -gcc-name=/usr/tce/packages/gcc/gcc-8.1.0/bin/gcc
        cxxflags: -gxx-name=/usr/tce/packages/gcc/gcc-8.1.0/bin/g++
        fflags: -gcc-name=/usr/tce/packages/gcc/gcc-8.1.0/bin/gcc
      modules: []
      operating_system: rhel7
      paths:
        cc:  /usr/tce/packages/intel/intel-19.0.4/bin/icc
        cxx: /usr/tce/packages/intel/intel-19.0.4/bin/icpc
        f77: /usr/tce/packages/intel/intel-19.0.4/bin/ifort
        fc:  /usr/tce/packages/intel/intel-19.0.4/bin/ifort
      spec: intel@19.0.4
      target: x86_64

  packages:
    all:
      # This defaults us to machine specific flags of ivybridge which allows
      # us to run on broadwell as well
      target: [ivybridge]
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [mvapich2]

    # LLNL toss3 CUDA
    cuda:
      buildable: false
      externals:
      - spec: cuda@10.2
        prefix: /opt/cudatoolkit/10.2

    # Lock down which MPI we are using
    mpi:
      buildable: false
    mvapich2:
      buildable: false
      externals:
      - spec: mvapich2@2.3%clang@9.0.0 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-clang-9.0.0
      - spec: mvapich2@2.3%clang@10.0.0 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-clang-10.0.0
      - spec: mvapich2@2.3%gcc@8.1.0 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-gcc-8.1.0
      - spec: mvapich2@2.3%gcc@8.3.1 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-gcc-8.3.1
      - spec: mvapich2@2.3%intel@19.0.4 process_managers=slurm arch=linux-rhel7-ivybridge
        prefix: /usr/tce/packages/mvapich2/mvapich2-2.3-intel-19.0.0

    # blas is a bit more complicated because its a virtual package so fake it with
    # the following per spack docs
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.6.1
        prefix: /usr

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.13.4
        prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.27
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.29.0
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.3
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.176
        prefix: /usr
    epoxy:
      buildable: false
      externals:
      - spec: epoxy@1.5.2
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.5.11
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.25
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.2
        prefix: /usr
    libunwind:
      buildable: false
      externals:
      - spec: libunwind@8.0.1
        prefix: /usr
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.20.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@6.2
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.26
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    zlib:
      buildable: false
      externals:
      - spec: zlib@1.2.7
        prefix: /usr


      # External dependencies for SCR
    lsf:
      buildable: False
      externals:
      - spec: lsf@10.1
        prefix: /opt/ibm/spectrumcomputing/lsf/10.1
    slurm:
      buildable: false
      externals:
      - spec: slurm@20
        prefix: /usr
    libyogrt:
      buildable: false
      externals:
      - spec: libyogrt@1.24 scheduler=lsf
        prefix: /usr
      - spec: libyogrt@1.24 scheduler=slurm
        prefix: /usr
    pdsh:
      buildable: false
      externals:
      - spec: pdsh@2.33
        prefix: /usr

    # Globally lock version of third party libraries
    camp:
      require: "@2023.06.0"
    conduit:
      require: "@0.8.8~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    hypre:
      version: [2.24.0]
    mfem:
      require: "@4.5.2"
    raja:
      require: "@2023.06.0~shared~examples~exercises"
    scr:
      require: "@3.0.1~shared~tests~examples"
    umpire:
      require: "@2023.06.0~shared~examples"

    # Globally lock in versions of Devtools
    cmake:
      version: [3.21.1]
      buildable: false
      externals:
      - spec: cmake@3.21.1
        prefix: /usr/tce/packages/cmake/cmake-3.21.1
    cppcheck:
      version: [2.9]
      buildable: false
      externals:
      - spec: cppcheck@2.9
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/cppcheck-2.9
    doxygen:
      version: [1.8.14]
      buildable: false
      externals:
      - spec: doxygen@1.8.14
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/doxygen-1.8.14
    graphviz:
      version: [7.1.0]
      buildable: false
      externals:
      - spec: graphviz@7.1.0
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/graphviz-7.1.0
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm@10.0.0+clang
        prefix: /usr/tce/packages/clang/clang-10.0.0
    python:
      version: [3.10.10]
      buildable: false
      externals:
      - spec: python@3.10.10
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.10.10
    py-shroud:
      version: [0.12.2]
      buildable: false
      externals:
      - spec: py-shroud@0.12.2
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.10.10
    py-sphinx:
      version: [6.1.3]
      buildable: false
      externals:
      - spec: py-sphinx@6.1.3
        prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.10.10
