#
# Makefile.lt
#

DS_SRC = ..  # Datastore source
VPATH = $(DS_SRC)

LIBOBJS = \
	DataObject.o \
	DataGroup.o \
	DatastoreInterface.o \
	DataFunctionCompiled.o \
	DataUserType.o \
	c-datastore.o

CLIBS =  -L. -lds -lstdc++
CXXLIBS = -L. -lds -L$(PACT)/lib -lpdb -lpml -lscore

CFLAGS = -O0 -g3 -std=c99 -I$(DS_SRC)
CXXFLAGS = -O0 -g3 -std=c++11 -Wall -Wextra -Wshadow -pedantic -Woverloaded-virtual -Wno-unused-variable -Wno-unused-parameter -Wno-return-type -I.. -I$(DS_SRC) -I$(PACT)/include -fpermissive
# -Wabi

work : testfunc.x

all : test1.x test1c.x

test1.x : test1.cpp libds.a

test1c.x : test1c.c libds.a

testfunc.x : testfunc.cpp libds.a

teststruct.x : teststruct.cpp testds.o libds.a

$(LIBOBJS) : Attributes.hpp DataGroup.hpp Types.hpp DataFunctionCompiled.hpp DataObject.hpp Utilities.hpp DataFunction.hpp DatastoreInterface.hpp

testds.o : DataUserType.hpp DataMember.hpp DatastoreInterface.hpp


libds.a : $(LIBOBJS)
	ar -rsc $@ $?

#DataGroup.o : $(DS_SRC)/DataGroup.cpp
%.o : %.cpp
	$(CXX) $(CXXFLAGS) $< -c -o $@

%.x : %.c
	$(CC) $(CFLAGS) -I$(DS_SRC) $< $(CLIBS) -o $@

%.x : %.cpp
	$(CXX) $(CXXFLAGS) -I$(DS_SRC) $^ $(CXXLIBS) -o $@
#	$(CXX) $(CXXFLAGS) -I$(DS_SRC) $< $(CXXLIBS) -o $@

clean : 
	rm -f *~ test*.x libds.a $(LIBOBJS) *.o

.PHONY : clean

