services: docker
dist: trusty
language: cpp
env:
  global:
  - DO_BUILD=yes
  - DO_TEST=yes
  - GTEST_COLOR=1
matrix:
  include:
  - compiler: gcc6
    env:
    - COMPILER=g++
    - IMG=gcc-6
    - CMAKE_EXTRA_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DAXOM_ENABLE_SIDRE=Off"
    - DO_MEMCHECK=yes
  - compiler: clang4
    env:
    - COMPILER=clang++
    - IMG=clang-4
    - CMAKE_EXTRA_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DENABLE_WARNINGS=On -DAXOM_ENABLE_SIDRE=Off"

script:
- docker run --rm --user='root' -v ${TRAVIS_BUILD_DIR}:/home/axom axom/compilers:$IMG chown -R axom /home/axom
- docker run --rm  -v ${TRAVIS_BUILD_DIR}:/home/axom -e COMPILER -e DO_BUILD -e DO_TEST -e DO_MEMCHECK -e CMAKE_EXTRA_FLAGS -e GTEST_COLOR axom/compilers:$IMG ./scripts/travis/build_and_test.sh

after_success:
- if [[ "${CMAKE_EXTRA_FLAGS}" == *"ENABLE_COVERAGE"* ]] ; then bash <(curl -s https://codecov.io/bash) -a "-f" >& /dev/null; fi
