#
# Copyright (c) 2017-2019, Lawrence Livermore National Security, LLC and
# other Axom Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)
#

ignore:
  - "src/thirdparty/fmt"
  - "src/thirdparty/sparsehash"
  - "test"

##coverage:
##  precision: 3
##  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: no
      macro: no
