# Copyright (c) 2017-2023, Lawrence Livermore National Security, LLC and
# Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/clang
        cxx: /usr/bin/clang++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: clang@10.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        cflags: -pthread
        cxxflags: -pthread
      modules: []
      operating_system: ubuntu20.04
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      spec: gcc@11.1.0
      target: x86_64

  packages:
    all:
      # This defaults us to machine specific flags of ivybridge which allows
      # us to run on broadwell as well
      target: [x86_64]
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        awk: [gawk]
        blas: [openblas]
        lapack: [openblas]
        daal: [intel-daal]
        elf: [elfutils]
        golang: [gcc]
        ipp: [intel-ipp]
        java: [jdk]
        mkl: [intel-mkl]
        mpe: [mpe2]
        mpi: [mpich]
        opencl: [pocl]
        openfoam: [openfoam-com, openfoam-org, foam-extend]
        pil: [py-pillow]
        scalapack: [netlib-scalapack]
        szip: [libszip, libaec]
        tbb: [intel-tbb]
        jpeg: [libjpeg-turbo, libjpeg]

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@3.3
        prefix: /usr

    # System level packages to not build
    autotools:
      buildable: false
      externals:
      - spec: autotools@2.69
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.1
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.1
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.29
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.40.1
        prefix: /usr
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.2.20
        prefix: /usr

    # Globally lock version of third party libraries
    camp:
      require: "@2023.06.0"
    conduit:
      require: "@0.8.8~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    hypre:
      version: [2.24.0]
    # do shared mfem to allow PIC flag in mfem
    mfem:
      require: "@4.5.2+shared~static"
    raja:
      require: "@2023.06.0~shared~examples~exercises"
    scr:
      require: "@develop~shared"
    umpire:
      require: "@2023.06.0~shared~examples"

    # Globally lock in version of devtools
    cmake:
      version: [3.21.7]
      buildable: false
      externals:
      - spec: cmake@3.21.7
        prefix: /usr
    doxygen:
      version: [1.8.17]
      buildable: false
      externals:
      - spec: doxygen@1.8.17
        prefix: /usr
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm@10.0.0+clang
        prefix: /usr
    py-sphinx:
      version: [1.8.5]
      buildable: false
      externals:
      - spec: py-sphinx@1.8.5
        prefix: /usr
