FROM axom/compilers:gcc-7

RUN sudo apt-get update -y
RUN sudo apt-get install curl -fy

RUN sudo apt-get -qq install -y --no-install-recommends gfortran-7 && sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 100

RUN git clone --recursive https://github.com/LLNL/axom.git

RUN git clone --recursive https://github.com/LLNL/RAJA.git

WORKDIR "/home/axom/RAJA"
RUN mkdir build

WORKDIR "/home/axom/RAJA/build"
RUN cmake ../. -DENABLE_TESTS=OFF
RUN make 
RUN sudo make install

WORKDIR "/home/axom/axom"

RUN ./scripts/uberenv/uberenv.py --spack-config-dir=./scripts/uberenv/spack_configs/docker --spec=%gcc@7.3.0 --prefix=/home/axom/axom_tpls -k

WORKDIR "/home/axom"

RUN rm -rf axom
