FROM axom/compilers:clang-10

# Update base image so we don't have to install so many things via Spack
SHELL ["/bin/bash", "-c"]
RUN sudo apt-get update -y
RUN sudo apt-get install curl ssh pkg-config build-essential libopenblas-dev mpich python3 cmake -fy
RUN sudo apt-get -qq install -y --no-install-recommends gfortran-7 && sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 100
RUN sudo ln -f -s python3 /usr/bin/python # Compatibility with legacy Python

WORKDIR "/home/axom"
USER axom

# Clone axom
RUN git clone -b feature/white238/addclang10docker --recursive https://github.com/LLNL/axom.git

# Build TPLs
WORKDIR "/home/axom/axom"
RUN python3 ./scripts/uberenv/uberenv.py --spack-config-dir=./scripts/uberenv/spack_configs/docker/ubuntu18 \
                                         --spec=%clang@10.0.0 --prefix=/home/axom/axom_tpls -k

# Make sure the new hostconfig worked
RUN python3 config-build.py -hc *.cmake -bp build && cd build && make -j && make -j test

# Copy host-config into easy location to copy out
RUN mkdir -p /home/axom/export_hostconfig
RUN cp ./axom/*.cmake /home/axom/export_hostconfig

# Clean up repository that will be cloned each CI job
WORKDIR "/home/axom"
RUN rm -rf axom
