; Supervisor config file to run the OpenVSCode server

[supervisord]
 nodaemon = true
 user = XXX
 logfile = /tmp/supervisord.log

[program:openvscode-server]
environment=HOME="/home/XXX",USER="XXX"
redirect_stderr = true
stdout_logfile = /var/log/openvscode-server.log
command = /opt/openvscode-server/bin/openvscode-server --without-connection-token --disable-telemetry --disable-workspace-trust --host 0.0.0.0 --default-folder /home/XXX/shaping_tutorial
