# Copyright (c) Lawrence Livermore National Security, LLC and other
# Axom Project Contributors. See top-level LICENSE and COPYRIGHT
# files for dates and other details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  include:
  - ../defaults.yaml
  - ../versions.yaml

  toolchains:
    gcc_12:
    - spec: '%c=gcc'
      when: '%c'
    - spec: '%cxx=gcc'
      when: '%cxx'
    - spec: '%fortran=gcc'
      when: '%fortran'
    - spec: '%mpich'
      when: '%mpi'

  packages:
    all:
      # This defaults us to machine specific flags of ivybridge which allows
      # us to run on broadwell as well
      target: [x86_64]
      providers:
        blas: [openblas]
        lapack: [openblas]
        mpi: [mpich]

    #Compiler packages
    gcc:
      externals:
      - spec: gcc@12.3.0 languages:=c,c++,fortran
        prefix: /usr/bin
        extra_attributes:
          compilers:
            cc: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran

    # Spack may grab for mpi & we don't want to use them
    mpi:
      buildable: false
    mpich:
      externals:
      - spec: mpich@4.0
        prefix: /usr

    # System level packages to not build
    autotools:
      buildable: false
      externals:
      - spec: autotools@2.69
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.3.0
        prefix: /usr/local/cuda
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.187
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.18
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.26.1
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.29.1
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.29
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.40.1
        prefix: /usr
    openblas:
      buildable: false
      externals:
      - spec: openblas@0.2.20
        prefix: /usr

    # Add some additional contraints to third party libraries
    # do shared mfem to allow PIC flag in mfem
    mfem:
      require: 
      - spec: "+shared~static"

    # Globally lock in version of devtools

    # RAJA needs cmake 3.24:
    # cmake:
    #   version: [3.23.1]
    #   buildable: false
    #   externals:
    #   - spec: cmake@3.23.1
    #     prefix: /usr/local
    doxygen:
      version: [1.8.17]
      buildable: false
      externals:
      - spec: doxygen@1.8.17
        prefix: /usr
    llvm:
      version: [10.0.0]
      buildable: false
      externals:
      - spec: llvm@10.0.0+clang
        prefix: /usr
    py-sphinx:
      version: [1.8.5]
      buildable: false
      externals:
      - spec: py-sphinx@1.8.5
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr
    python:
      version: [3.10.12]
      buildable: false
      externals:
      - spec: python@3.10.12
        prefix: /usr
