/* This file was generated by PyBindGen 0.17.0 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stddef.h>


#if PY_VERSION_HEX < 0x020400F0

#define PyEval_ThreadsInitialized() 1

#define Py_CLEAR(op)				\
        do {                            	\
                if (op) {			\
                        PyObject *tmp = (PyObject *)(op);	\
                        (op) = NULL;		\
                        Py_DECREF(tmp);		\
                }				\
        } while (0)


#define Py_VISIT(op)							\
        do { 								\
                if (op) {						\
                        int vret = visit((PyObject *)(op), arg);	\
                        if (vret)					\
                                return vret;				\
                }							\
        } while (0)

#endif



#if PY_VERSION_HEX < 0x020500F0

typedef int Py_ssize_t;
# define PY_SSIZE_T_MAX INT_MAX
# define PY_SSIZE_T_MIN INT_MIN
typedef inquiry lenfunc;
typedef intargfunc ssizeargfunc;
typedef intobjargproc ssizeobjargproc;

#endif


#ifndef PyVarObject_HEAD_INIT
#define PyVarObject_HEAD_INIT(type, size) \
        PyObject_HEAD_INIT(type) size,
#endif


#if PY_VERSION_HEX >= 0x03000000
typedef void* cmpfunc;
#define PyCObject_FromVoidPtr(a, b) PyCapsule_New(a, NULL, b)
#define PyCObject_AsVoidPtr(a) PyCapsule_GetPointer(a, NULL)
#define PyString_FromString(a) PyBytes_FromString(a)
#define Py_TPFLAGS_CHECKTYPES 0 /* this flag doesn't exist in python 3 */
#endif


#if     __GNUC__ > 2
# define PYBINDGEN_UNUSED(param) param __attribute__((__unused__))
#elif     __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4)
# define PYBINDGEN_UNUSED(param) __attribute__((__unused__)) param
#else
# define PYBINDGEN_UNUSED(param) param
#endif  /* !__GNUC__ */

#ifndef _PyBindGenWrapperFlags_defined_
#define _PyBindGenWrapperFlags_defined_
typedef enum _PyBindGenWrapperFlags {
   PYBINDGEN_WRAPPER_FLAG_NONE = 0,
   PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED = (1<<0),
} PyBindGenWrapperFlags;
#endif


#include "VectorXY.hpp"
/* --- forward declarations --- */


typedef struct {
    PyObject_HEAD
    VectorXY *obj;
    PyBindGenWrapperFlags flags:8;
} PyVectorXY;


extern PyTypeObject PyVectorXY_Type;

static PyMethodDef vectorXY_functions[] = {
    {NULL, NULL, 0, NULL}
};
/* --- classes --- */


static PyObject* _wrap_PyVectorXY__get_x(PyVectorXY *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "d", self->obj->x);
    return py_retval;
}
static int _wrap_PyVectorXY__set_x(PyVectorXY *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "d", &self->obj->x)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyObject* _wrap_PyVectorXY__get_y(PyVectorXY *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "d", self->obj->y);
    return py_retval;
}
static int _wrap_PyVectorXY__set_y(PyVectorXY *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "d", &self->obj->y)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyGetSetDef PyVectorXY__getsets[] = {
    {
        (char*) "y", /* attribute name */
        (getter) _wrap_PyVectorXY__get_y, /* C function to get the attribute */
        (setter) _wrap_PyVectorXY__set_y, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    {
        (char*) "x", /* attribute name */
        (getter) _wrap_PyVectorXY__get_x, /* C function to get the attribute */
        (setter) _wrap_PyVectorXY__set_x, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    { NULL, NULL, NULL, NULL, NULL }
};


static int
_wrap_PyVectorXY__tp_init__0(PyVectorXY *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    const char *keywords[] = {NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new VectorXY();
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static int
_wrap_PyVectorXY__tp_init__1(PyVectorXY *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    double x;
    double y;
    const char *keywords[] = {"x", "y", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "dd", (char **) keywords, &x, &y)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new VectorXY(x, y);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

int _wrap_PyVectorXY__tp_init(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    int retval;
    PyObject *error_list;
    PyObject *exceptions[2] = {0,};
    retval = _wrap_PyVectorXY__tp_init__0(self, args, kwargs, &exceptions[0]);
    if (!exceptions[0]) {
        return retval;
    }
    retval = _wrap_PyVectorXY__tp_init__1(self, args, kwargs, &exceptions[1]);
    if (!exceptions[1]) {
        Py_DECREF(exceptions[0]);
        return retval;
    }
    error_list = PyList_New(2);
    PyList_SET_ITEM(error_list, 0, PyObject_Str(exceptions[0]));
    Py_DECREF(exceptions[0]);
    PyList_SET_ITEM(error_list, 1, PyObject_Str(exceptions[1]));
    Py_DECREF(exceptions[1]);
    PyErr_SetObject(PyExc_TypeError, error_list);
    Py_DECREF(error_list);
    return -1;
}


PyObject *
_wrap_PyVectorXY_scale(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    double s;
    const char *keywords[] = {"s", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "d", (char **) keywords, &s)) {
        return NULL;
    }
    self->obj->scale(s);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_sub(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    PyVectorXY *b;
    const char *keywords[] = {"b", NULL};
    PyVectorXY *py_VectorXY;

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyVectorXY_Type, &b)) {
        return NULL;
    }
    VectorXY retval = self->obj->sub(*((PyVectorXY *) b)->obj);
    py_VectorXY = PyObject_New(PyVectorXY, &PyVectorXY_Type);
    py_VectorXY->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    py_VectorXY->obj = new VectorXY(retval);
    py_retval = Py_BuildValue((char *) "N", py_VectorXY);
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_elim(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    PyVectorXY *b;
    const char *keywords[] = {"b", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyVectorXY_Type, &b)) {
        return NULL;
    }
    self->obj->elim(*((PyVectorXY *) b)->obj);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_cross(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    double retval;
    PyVectorXY *v;
    const char *keywords[] = {"v", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyVectorXY_Type, &v)) {
        return NULL;
    }
    retval = self->obj->cross(*((PyVectorXY *) v)->obj);
    py_retval = Py_BuildValue((char *) "d", retval);
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_add(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    PyVectorXY *a;
    const char *keywords[] = {"a", NULL};
    PyVectorXY *py_VectorXY;

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyVectorXY_Type, &a)) {
        return NULL;
    }
    VectorXY retval = self->obj->add(*((PyVectorXY *) a)->obj);
    py_VectorXY = PyObject_New(PyVectorXY, &PyVectorXY_Type);
    py_VectorXY->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    py_VectorXY->obj = new VectorXY(retval);
    py_retval = Py_BuildValue((char *) "N", py_VectorXY);
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_mag(PyVectorXY *self)
{
    PyObject *py_retval;
    double retval;

    retval = self->obj->mag();
    py_retval = Py_BuildValue((char *) "d", retval);
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_mag2(PyVectorXY *self)
{
    PyObject *py_retval;
    double retval;

    retval = self->obj->mag2();
    py_retval = Py_BuildValue((char *) "d", retval);
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_accum(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    PyVectorXY *b;
    const char *keywords[] = {"b", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyVectorXY_Type, &b)) {
        return NULL;
    }
    self->obj->accum(*((PyVectorXY *) b)->obj);
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject *
_wrap_PyVectorXY_mult(PyVectorXY *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    double s;
    const char *keywords[] = {"s", NULL};
    PyVectorXY *py_VectorXY;

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "d", (char **) keywords, &s)) {
        return NULL;
    }
    VectorXY retval = self->obj->mult(s);
    py_VectorXY = PyObject_New(PyVectorXY, &PyVectorXY_Type);
    py_VectorXY->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    py_VectorXY->obj = new VectorXY(retval);
    py_retval = Py_BuildValue((char *) "N", py_VectorXY);
    return py_retval;
}

static PyMethodDef PyVectorXY_methods[] = {
    {(char *) "scale", (PyCFunction) _wrap_PyVectorXY_scale, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "sub", (PyCFunction) _wrap_PyVectorXY_sub, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "elim", (PyCFunction) _wrap_PyVectorXY_elim, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "cross", (PyCFunction) _wrap_PyVectorXY_cross, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "add", (PyCFunction) _wrap_PyVectorXY_add, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "mag", (PyCFunction) _wrap_PyVectorXY_mag, METH_NOARGS, NULL },
    {(char *) "mag2", (PyCFunction) _wrap_PyVectorXY_mag2, METH_NOARGS, NULL },
    {(char *) "accum", (PyCFunction) _wrap_PyVectorXY_accum, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "mult", (PyCFunction) _wrap_PyVectorXY_mult, METH_KEYWORDS|METH_VARARGS, NULL },
    {NULL, NULL, 0, NULL}
};

static void
_wrap_PyVectorXY__tp_dealloc(PyVectorXY *self)
{
        VectorXY *tmp = self->obj;
        self->obj = NULL;
        if (!(self->flags&PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED)) {
            delete tmp;
        }
    Py_TYPE(self)->tp_free((PyObject*)self);
}

static PyObject*
_wrap_PyVectorXY__tp_richcompare (PyVectorXY *PYBINDGEN_UNUSED(self), PyVectorXY *other, int opid)
{

    if (!PyObject_IsInstance((PyObject*) other, (PyObject*) &PyVectorXY_Type)) {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }
    switch (opid)
    {
    case Py_LT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_LE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_EQ:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_NE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    } /* closes switch (opid) */
    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}

PyTypeObject PyVectorXY_Type = {
    PyVarObject_HEAD_INIT(NULL, 0)
    (char *) "vectorXY.VectorXY",            /* tp_name */
    sizeof(PyVectorXY),                  /* tp_basicsize */
    0,                                 /* tp_itemsize */
    /* methods */
    (destructor)_wrap_PyVectorXY__tp_dealloc,        /* tp_dealloc */
    (printfunc)0,                      /* tp_print */
    (getattrfunc)NULL,       /* tp_getattr */
    (setattrfunc)NULL,       /* tp_setattr */
    (cmpfunc)NULL,           /* tp_compare */
    (reprfunc)NULL,             /* tp_repr */
    (PyNumberMethods*)NULL,     /* tp_as_number */
    (PySequenceMethods*)NULL, /* tp_as_sequence */
    (PyMappingMethods*)NULL,   /* tp_as_mapping */
    (hashfunc)NULL,             /* tp_hash */
    (ternaryfunc)NULL,          /* tp_call */
    (reprfunc)NULL,              /* tp_str */
    (getattrofunc)NULL,     /* tp_getattro */
    (setattrofunc)NULL,     /* tp_setattro */
    (PyBufferProcs*)NULL,  /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,                      /* tp_flags */
    NULL,                        /* Documentation string */
    (traverseproc)NULL,     /* tp_traverse */
    (inquiry)NULL,             /* tp_clear */
    (richcmpfunc)_wrap_PyVectorXY__tp_richcompare,   /* tp_richcompare */
    0,             /* tp_weaklistoffset */
    (getiterfunc)NULL,          /* tp_iter */
    (iternextfunc)NULL,     /* tp_iternext */
    (struct PyMethodDef*)PyVectorXY_methods, /* tp_methods */
    (struct PyMemberDef*)0,              /* tp_members */
    PyVectorXY__getsets,                     /* tp_getset */
    NULL,                              /* tp_base */
    NULL,                              /* tp_dict */
    (descrgetfunc)NULL,    /* tp_descr_get */
    (descrsetfunc)NULL,    /* tp_descr_set */
    0,                 /* tp_dictoffset */
    (initproc)_wrap_PyVectorXY__tp_init,             /* tp_init */
    (allocfunc)PyType_GenericAlloc,           /* tp_alloc */
    (newfunc)PyType_GenericNew,               /* tp_new */
    (freefunc)0,             /* tp_free */
    (inquiry)NULL,             /* tp_is_gc */
    NULL,                              /* tp_bases */
    NULL,                              /* tp_mro */
    NULL,                              /* tp_cache */
    NULL,                              /* tp_subclasses */
    NULL,                              /* tp_weaklist */
    (destructor) NULL                  /* tp_del */
};


#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef vectorXY_moduledef = {
    PyModuleDef_HEAD_INIT,
    "vectorXY",
    NULL,
    -1,
    vectorXY_functions,
};
#endif


#if PY_VERSION_HEX >= 0x03000000
    #define MOD_ERROR NULL
    #define MOD_INIT(name) PyObject* PyInit_##name(void)
    #define MOD_RETURN(val) val
#else
    #define MOD_ERROR
    #define MOD_INIT(name) void init##name(void)
    #define MOD_RETURN(val)
#endif
#if defined(__cplusplus)
extern "C"
#endif
#if defined(__GNUC__) && __GNUC__ >= 4
__attribute__ ((visibility("default")))
#endif


MOD_INIT(vectorXY)
{
    PyObject *m;
    #if PY_VERSION_HEX >= 0x03000000
    m = PyModule_Create(&vectorXY_moduledef);
    #else
    m = Py_InitModule3((char *) "vectorXY", vectorXY_functions, NULL);
    #endif
    if (m == NULL) {
        return MOD_ERROR;
    }
    /* Register the 'VectorXY' class */
    if (PyType_Ready(&PyVectorXY_Type)) {
        return MOD_ERROR;
    }
    PyModule_AddObject(m, (char *) "VectorXY", (PyObject *) &PyVectorXY_Type);
    return MOD_RETURN(m);
}
