# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      mpi: [cray-mpich]

  hip:
    version: [4.3.1]
    buildable: false
    externals:
    - spec: hip@4.3.1
      prefix: /opt/rocm-4.3.1/hip

  llvm-amdgpu:
    version: [4.3.1]
    buildable: false
    externals:
    - spec: llvm-amdgpu@4.3.1
      prefix: /opt/rocm-4.3.1/llvm

  hsa-rocr-dev:
    version: [4.3.1]
    buildable: false
    externals:
    - spec: hsa-rocr-dev@4.3.1
      prefix: /opt/rocm-4.3.1/

  rocminfo:
    version: [4.3.1]
    buildable: false
    externals:
    - spec: rocminfo@4.3.1
      prefix: /opt/rocm-4.3.1/

  rocm-device-libs:
    version: [4.3.1]
    buildable: false
    externals:
    - spec: rocm-device-libs@4.3.1
      prefix: /opt/rocm-4.3.1/

# Lock down which MPI we are using
  mpi:
    buildable: false
  cray-mpich:
    buildable: false
    externals:
    #- spec: cray-mpich@8.1.7%clang@13.0.0
    #  prefix: /opt/cray/pe/mpich/8.1.9/ofi/amd/4.3
    - spec: cray-mpich@8.1.9%clang@13.0.0_hip_no_fortran+slurm
      prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.9-rocmcc-4.3.1/

  # blas is a bit more complicated because its a virtual package so fake it with
  # the following per spack docs
  netlib-lapack:
    buildable: false
    externals:
    - spec: netlib-lapack@3.6.1
      prefix: /usr

# System level packages to not build
  autoconf:
    buildable: false
    externals:
    - spec: autoconf
      prefix: /usr
  automake:
    buildable: false
    externals:
    - spec: automake
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2
      prefix: /usr
  cmake:
    version: [3.19.2]
    buildable: false
    externals:
    - spec: cmake
      prefix: /usr/tce/packages/cmake/cmake-3.19.2
  gettext:
    buildable: false
    externals:
    - spec: gettext
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config
      prefix: /usr
  tar:
    buildable: false
    externals:
    - spec: tar
      prefix: /usr

# External dependencies for SCR
  lsf:
    buildable: False
    externals:
    - spec: lsf@10.1
      prefix: /opt/ibm/spectrumcomputing/lsf/10.1
  slurm:
    buildable: false
    externals:
    - spec: slurm@20
      prefix: /usr
  libyogrt:
    externals:
    - spec: libyogrt@1.24 scheduler=lsf
      prefix: /usr
    - spec: libyogrt@1.24 scheduler=slurm
      prefix: /usr
  pdsh:
    buildable: false
    externals:
    - spec: pdsh@2.33
      prefix: /usr 

# Globally lock version of third party libraries
  conduit:
    version: [0.7.2axom]
    variants: ~shared~test~fortran
  hdf5:
    variants: ~shared~mpi
  mfem:
    variants: ~mpi~metis~zlib
  raja:
    variants: ~shared~examples~exercises
  scr:
    version: [develop]
    variants: ~shared
  umpire:
    variants: ~shared~examples

# Globally lock in versions of Devtools
  cppcheck:
    version: [1.87]
    buildable: false
    externals:
    - spec: cppcheck
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/cppcheck-1.87
  doxygen:
    version: [1.8.14]
    buildable: false
    externals:
    - spec: doxygen
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/doxygen-1.8.14
  graphviz:
    version: [2.42.2]
    buildable: false
    externals:
    - spec: graphviz
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/graphviz-2.42.2
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm+clang
      prefix: /usr/tce/packages/clang/clang-10.0.0
  python:
    version: [3.7.7]
    buildable: false
    externals:
    - spec: python
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7
  py-shroud:
    version: [0.12.2]
    buildable: false
    externals:
    - spec: py-shroud
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7
  py-sphinx:
    version: [2.2.0]
    buildable: false
    externals:
    - spec: py-sphinx
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7
