# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      mpi: [cray-mpich]

  hip:
    version: [4.5.2]
    buildable: false
    externals:
    - spec: hip@4.5.2
      prefix: /opt/rocm-4.5.2/hip

  llvm-amdgpu:
    version: [4.5.2]
    buildable: false
    externals:
    - spec: llvm-amdgpu@4.5.2
      prefix: /opt/rocm-4.5.2/llvm

  hsa-rocr-dev:
    version: [4.5.2]
    buildable: false
    externals:
    - spec: hsa-rocr-dev@4.5.2
      prefix: /opt/rocm-4.5.2/

  rocminfo:
    version: [4.5.2]
    buildable: false
    externals:
    - spec: rocminfo@4.5.2
      prefix: /opt/rocm-4.5.2/

  rocm-device-libs:
    version: [4.5.2]
    buildable: false
    externals:
    - spec: rocm-device-libs@4.5.2
      prefix: /opt/rocm-4.5.2/

# Lock down which MPI we are using
  mpi:
    buildable: false
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.13%clang@13.0.0+slurm
      prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.13-rocmcc-4.5.2-cce-13.0.1/

  # blas is a bit more complicated because its a virtual package so fake it with
  # the following per spack docs
  netlib-lapack:
    buildable: false
    externals:
    - spec: netlib-lapack@3.6.1
      prefix: /usr

# System level packages to not build
  autoconf:
    buildable: false
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    buildable: false
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  binutils:
    buildable: false
    externals:
    - spec: binutils@2.27
      prefix: /usr
  bzip2:
    buildable: false
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  diffutils:
    buildable: false
    externals:
    - spec: diffutils@3.3
      prefix: /usr
  elfutils:
    buildable: false
    externals:
    - spec: elfutils@0.176
      prefix: /usr
  epoxy:
    buildable: false
    externals:
    - spec: epoxy@1.5.2
      prefix: /usr
  findutils:
    buildable: false
    externals:
    - spec: findutils@4.5.11
      prefix: /usr
  gettext:
    buildable: false
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  ghostscript:
    buildable: false
    externals:
    - spec: ghostscript@9.25
      prefix: /usr
  groff:
    buildable: false
    externals:
    - spec: groff@1.22.2
      prefix: /usr
  graphviz:
    buildable: false
    externals:
    - spec: graphviz@2.30.1
      prefix: /usr
  libtool:
    buildable: false
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  libunwind:
    buildable: false
    externals:
    - spec: libunwind@8.0.1
      prefix: /usr
  libx11:
    buildable: false
    externals:
    - spec: libx11@1.20.4
      prefix: /usr
  m4:
    buildable: false
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl@5.16.3
      prefix: /usr
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config@0.27.1
      prefix: /usr
  readline:
    buildable: false
    externals:
    - spec: readline@6.2
      prefix: /usr
  tar:
    buildable: false
    externals:
    - spec: tar@1.26
      prefix: /usr
  unzip:
    buildable: false
    externals:
    - spec: unzip@6.0
      prefix: /usr
  zlib:
    buildable: false
    externals:
    - spec: zlib@1.2.7
      prefix: /usr
  curl:
    buildable: false
    externals:
    - spec: curl@7.61.1
      prefix: /usr

# External dependencies for SCR
  lsf:
    buildable: False
    externals:
    - spec: lsf@10.1
      prefix: /opt/ibm/spectrumcomputing/lsf/10.1
  slurm:
    buildable: false
    externals:
    - spec: slurm@20
      prefix: /usr
  libyogrt:
    externals:
    - spec: libyogrt@1.24 scheduler=lsf
      prefix: /usr
    - spec: libyogrt@1.24 scheduler=slurm
      prefix: /usr
  pdsh:
    buildable: false
    externals:
    - spec: pdsh@2.33
      prefix: /usr

# Globally lock version of third party libraries
  conduit:
    version: [0.7.2axom]
    variants: ~shared~test
  hdf5:
    variants: ~shared~mpi
  hypre:
    version: [2.20.0]
  mfem:
    version: [4.2.0]
  raja:
    variants: ~shared~examples~exercises
  umpire:
    version: [6.0.0axom]
    variants: ~shared~examples

# Globally lock in versions of Devtools
  cmake:
    version: [3.21.1]
    buildable: false
    externals:
    - spec: cmake@3.21.1
      prefix: /usr/tce/packages/cmake/cmake-3.21.1
  cppcheck:
    version: [1.87]
    buildable: false
    externals:
    - spec: cppcheck@1.87
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/cppcheck-1.87
  doxygen:
    version: [1.8.14]
    buildable: false
    externals:
    - spec: doxygen@1.8.14
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/doxygen-1.8.14
  graphviz:
    version: [2.42.2]
    buildable: false
    externals:
    - spec: graphviz@2.42.2
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/graphviz-2.42.2
  llvm:
    version: [10.0.0]
    buildable: false
    externals:
    - spec: llvm@10.0.0+clang
      prefix: /usr/tce/packages/clang/clang-10.0.0
  python:
    version: [3.7.7]
    buildable: false
    externals:
    - spec: python@3.7.7
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7
  py-shroud:
    version: [0.12.2]
    buildable: false
    externals:
    - spec: py-shroud@0.12.2
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7
  py-sphinx:
    version: [2.2.0]
    buildable: false
    externals:
    - spec: py-sphinx@2.2.0
      prefix: /collab/usr/gapps/axom/devtools/toss_3_x86_64_ib/latest/python-3.7.7