# Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
# Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  # Target specific AMD GPU architectures for specific machines:
  #
  # - Use amdgpu_target=gfx942 for rzadams
  # - Use amdgpu_target=gfx90a for tioga/rzvernal
  # - Use amdgpu_target=gfx908 for rznevada
  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.2.3/llvm/bin/amdclang
        cxx: /opt/rocm-5.2.3/llvm/bin/amdclang++
        f77: /opt/rocm-5.2.3/llvm/bin/amdflang
        fc: /opt/rocm-5.2.3/llvm/bin/amdflang
      spec: clang@14.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.4.3/llvm/bin/amdclang
        cxx: /opt/rocm-5.4.3/llvm/bin/amdclang++
        f77: /opt/rocm-5.4.3/llvm/bin/amdflang
        fc: /opt/rocm-5.4.3/llvm/bin/amdflang
      spec: clang@15.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.6.0/llvm/bin/amdclang
        cxx: /opt/rocm-5.6.0/llvm/bin/amdclang++
        f77: /opt/rocm-5.6.0/llvm/bin/amdflang
        fc: /opt/rocm-5.6.0/llvm/bin/amdflang
      spec: clang@16.0.0
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-5.7.1/llvm/bin/amdclang
        cxx: /opt/rocm-5.7.1/llvm/bin/amdclang++
        f77: /opt/rocm-5.7.1/llvm/bin/amdflang
        fc: /opt/rocm-5.7.1/llvm/bin/amdflang
      spec: rocmcc@=5.7.1
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-6.1.2/llvm/bin/amdclang
        cxx: /opt/rocm-6.1.2/llvm/bin/amdclang++
        f77: /opt/rocm-6.1.2/llvm/bin/amdflang
        fc: /opt/rocm-6.1.2/llvm/bin/amdflang
      spec: rocmcc@=6.1.2
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      flags:
        fflags: -Mfreeform
      modules: []
      operating_system: rhel8
      paths:
        cc: /opt/rocm-6.2.1/llvm/bin/amdclang
        cxx: /opt/rocm-6.2.1/llvm/bin/amdclang++
        f77: /opt/rocm-6.2.1/llvm/bin/amdflang
        fc: /opt/rocm-6.2.1/llvm/bin/amdflang
      spec: rocmcc@=6.2.1
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      # Flag for lowercase Fortran module names
      flags:
        fflags: -ef
      modules: []
      operating_system: rhel8
      paths:
        cc: /usr/tce/packages/cce-tce/cce-15.0.1/bin/craycc
        cxx: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayCC
        f77: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayftn
        fc: /usr/tce/packages/cce-tce/cce-15.0.1/bin/crayftn
      spec: cce@15.0.1
      target: x86_64
  - compiler:
      environment: {}
      extra_rpaths: []
      # Flag for lowercase Fortran module names
      flags:
        fflags: -ef
      modules: []
      operating_system: rhel8
      paths:
        cc: /usr/tce/packages/cce-tce/cce-18.0.0/bin/craycc
        cxx: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayCC
        f77: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayftn
        fc: /usr/tce/packages/cce-tce/cce-18.0.0/bin/crayftn
      spec: cce@=18.0.0
      target: x86_64

  packages:
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        blas: [netlib-lapack]
        lapack: [netlib-lapack]
        mpi: [cray-mpich]
        zlib-api: [zlib]


    hip:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: hip@5.2.3
        prefix: /opt/rocm-5.2.3/hip
      - spec: hip@5.4.3
        prefix: /opt/rocm-5.4.3/hip
      - spec: hip@5.6.0
        prefix: /opt/rocm-5.6.0/hip
      - spec: hip@5.7.1
        prefix: /opt/rocm-5.7.1/hip
      - spec: hip@6.1.2
        prefix: /opt/rocm-6.1.2
      - spec: hip@6.2.1
        prefix: /opt/rocm-6.2.1

    llvm-amdgpu:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: llvm-amdgpu@5.2.3
        prefix: /opt/rocm-5.2.3/llvm
      - spec: llvm-amdgpu@5.4.3
        prefix: /opt/rocm-5.4.3/llvm
      - spec: llvm-amdgpu@5.6.0
        prefix: /opt/rocm-5.6.0/llvm
      - spec: llvm-amdgpu@5.7.1
        prefix: /opt/rocm-5.7.1/llvm
      - spec: llvm-amdgpu@6.1.2
        prefix: /opt/rocm-6.1.2/llvm
      - spec: llvm-amdgpu@6.2.1
        prefix: /opt/rocm-6.2.1/llvm

    hsa-rocr-dev:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: hsa-rocr-dev@5.2.3
        prefix: /opt/rocm-5.2.3/
      - spec: hsa-rocr-dev@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: hsa-rocr-dev@5.6.0
        prefix: /opt/rocm-5.6.0/
      - spec: hsa-rocr-dev@5.7.1
        prefix: /opt/rocm-5.7.1/
      - spec: hsa-rocr-dev@6.1.2
        prefix: /opt/rocm-6.1.2/
      - spec: hsa-rocr-dev@6.2.1
        prefix: /opt/rocm-6.2.1/

    rocblas:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: rocblas@5.2.3
        prefix: /opt/rocm-5.2.3/
      - spec: rocblas@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocblas@5.6.0
        prefix: /opt/rocm-5.6.0/
      - spec: rocblas@5.7.1
        prefix: /opt/rocm-5.7.1/
      - spec: rocblas@6.1.2
        prefix: /opt/rocm-6.1.2/
      - spec: rocblas@6.2.1
        prefix: /opt/rocm-6.2.1/

    rocminfo:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: rocminfo@5.2.3
        prefix: /opt/rocm-5.2.3/
      - spec: rocminfo@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocminfo@5.6.0
        prefix: /opt/rocm-5.6.0/
      - spec: rocminfo@5.7.1
        prefix: /opt/rocm-5.7.1
      - spec: rocminfo@6.1.2
        prefix: /opt/rocm-6.1.2
      - spec: rocminfo@6.2.1
        prefix: /opt/rocm-6.2.1

    rocprim:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: rocprim@5.2.3
        prefix: /opt/rocm-5.2.3/
      - spec: rocprim@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocprim@5.6.0
        prefix: /opt/rocm-5.6.0/
      - spec: rocprim@5.7.1
        prefix: /opt/rocm-5.7.1/
      - spec: rocprim@6.1.2
        prefix: /opt/rocm-6.1.2/
      - spec: rocprim@6.2.1
        prefix: /opt/rocm-6.2.1/

    rocm-device-libs:
      version: [5.2.3, 5.4.3, 5.6.0, 5.7.1, 6.1.2, 6.2.1]
      buildable: false
      externals:
      - spec: rocm-device-libs@5.2.3
        prefix: /opt/rocm-5.2.3/
      - spec: rocm-device-libs@5.4.3
        prefix: /opt/rocm-5.4.3/
      - spec: rocm-device-libs@5.6.0
        prefix: /opt/rocm-5.6.0/
      - spec: rocm-device-libs@5.7.1
        prefix: /opt/rocm-5.7.1/
      - spec: rocm-device-libs@6.1.2
        prefix: /opt/rocm-6.1.2/
      - spec: rocm-device-libs@6.2.1
        prefix: /opt/rocm-6.2.1/

    # Lock down which MPI we are using
    mpi:
      buildable: false
    cray-mpich:
      buildable: false
      externals:
      - spec: cray-mpich@8.1.16%clang@14.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.16-rocmcc-5.2.3/
      - spec: cray-mpich@8.1.25%clang@15.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.4.3/
      - spec: cray-mpich@8.1.25%clang@16.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.6.0/
      - spec: cray-mpich@8.1.27%rocmcc@5.7.1+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/
      - spec: cray-mpich@8.1.29%rocmcc@6.1.2+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.29-rocmcc-6.1.2/
      - spec: cray-mpich@8.1.29%rocmcc@6.2.1+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.29-rocmcc-6.2.1/
      - spec: cray-mpich@8.1.25%cce@15.0.1+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.25-rocmcc-5.4.3-cce-15.0.1/
      - spec: cray-mpich@8.1.29%cce@18.0.0+slurm
        prefix: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.29-rocmcc-6.1.2-cce-18.0.0/

    # blas is a bit more complicated because its a virtual package so fake it with
    # the following per spack docs
    netlib-lapack:
      buildable: false
      externals:
      - spec: netlib-lapack@3.6.1
        prefix: /usr

    # System level packages to not build
    autoconf:
      buildable: false
      externals:
      - spec: autoconf@2.69
        prefix: /usr
    automake:
      buildable: false
      externals:
      - spec: automake@1.13.4
        prefix: /usr
    binutils:
      buildable: false
      externals:
      - spec: binutils@2.27
        prefix: /usr
    bzip2:
      buildable: false
      externals:
      - spec: bzip2@1.0.6
        prefix: /usr
    curl:
      buildable: false
      externals:
      - spec: curl@7.61.1
        prefix: /usr
    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.3
        prefix: /usr
    elfutils:
      buildable: false
      externals:
      - spec: elfutils@0.176
        prefix: /usr
    epoxy:
      buildable: false
      externals:
      - spec: epoxy@1.5.2
        prefix: /usr
    findutils:
      buildable: false
      externals:
      - spec: findutils@4.5.11
        prefix: /usr
    gettext:
      buildable: false
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
    ghostscript:
      buildable: false
      externals:
      - spec: ghostscript@9.25
        prefix: /usr
    git:
      buildable: false
      externals:
      - spec: git@2.45.0
        prefix: /collab/usr/global/tools/tce4/opt/git-2.45.0
    gmake:
      buildable: false
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
    groff:
      buildable: false
      externals:
      - spec: groff@1.22.2
        prefix: /usr
    graphviz:
      buildable: false
      externals:
      - spec: graphviz@2.30.1
        prefix: /usr
    libtool:
      buildable: false
      externals:
      - spec: libtool@2.4.2
        prefix: /usr
    libunwind:
      buildable: false
      externals:
      - spec: libunwind@8.0.1
        prefix: /usr
    libx11:
      buildable: false
      externals:
      - spec: libx11@1.20.4
        prefix: /usr
    m4:
      buildable: false
      externals:
      - spec: m4@1.4.16
        prefix: /usr
    ncurses:
      externals:
      - spec: ncurses@6.1.20180224+termlib abi=6
        prefix: /usr
      buildable: false
    perl:
      buildable: false
      externals:
      - spec: perl@5.16.3
        prefix: /usr
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config@0.27.1
        prefix: /usr
    readline:
      buildable: false
      externals:
      - spec: readline@6.2
        prefix: /usr
    tar:
      buildable: false
      externals:
      - spec: tar@1.26
        prefix: /usr
    unzip:
      buildable: false
      externals:
      - spec: unzip@6.0
        prefix: /usr

    # External dependencies for opencascade
    # libx* versions found via `strings /path/to/libx*.so
    mesa:
      buildable: False
      externals:
      - spec: mesa@23.1.4  # found via: glxinfo | grep -i version
        prefix: /
    libxi:
      buildable: False
      externals:
      - spec: libxi@1.7.10
        prefix: /
    libxt:
      buildable: False
      externals:
      - spec: libxt@1.1.5
        prefix: /
    libxext:
      buildable: False
      externals:
      - spec: libxext@1.3.4
        prefix: /
    libxmu:
      buildable: False
      externals:
      - spec: libxmu@1.1.3
        prefix: /

    # External dependencies for SCR
    lsf:
      buildable: False
      externals:
      - spec: lsf@10.1
        prefix: /opt/ibm/spectrumcomputing/lsf/10.1
    slurm:
      buildable: false
      externals:
      - spec: slurm@20
        prefix: /usr
    libyogrt:
      externals:
      - spec: libyogrt@1.24 scheduler=lsf
        prefix: /usr
      - spec: libyogrt@1.24 scheduler=slurm
        prefix: /usr
    pdsh:
      buildable: false
      externals:
      - spec: pdsh@2.33
        prefix: /usr

    # Globally lock version of third party libraries
    adiak:
      require: "@0.4.0"
    caliper:
      require: "@2.10.0~kokkos"
    camp:
      require: "@2024.07.0"
    conduit:
      require: "@0.9.2~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    hypre:
      version: [2.24.0]
    mfem:
      require: "@4.6.0"
    py-jsonschema:
      require: "@:4.17" #Anything after this requires py-rpds which requires rust and adds 40 minutes
    raja:
      require: "@2024.07.0~shared~examples~exercises"
    scr:
      require: "@3.0.1~shared~tests~examples"
    umpire:
      require: "@2024.07.0~shared~examples~werror"

    # Failure with cce compiler:
    # https://github.com/besser82/libxcrypt/issues/181
    # Fix:
    # https://github.com/NixOS/nixpkgs/pull/309884
    libxcrypt:
      require:
      - ldflags=-Wl,--undefined-version

    # cce compiler requires static zlib
    zlib:
      variants: ~shared

    # Lock in versions of Devtools
    # Devtools are built on rzvernal for compatibility with both
    # rzvernal and rzadams.
    cmake:
      version: [3.24.2]
      buildable: false
      externals:
      - spec: cmake@3.24.2
        prefix: /usr/tce
    py-shroud:
      version: [0.13.0]
      buildable: false
      externals:
      - spec: py-shroud@0.13.0
        prefix: /collab/usr/gapps/shroud/public/toss_4_x86_64_ib_cray/shroud-0.13.0
    cppcheck:
      version: [2.9]
      buildable: false
      externals:
      - spec: cppcheck@2.9
        prefix: /collab/usr/gapps/axom/devtools/toss_4_x86_64_ib_cray/latest/cppcheck-2.9
    doxygen:
      version: [1.11.0]
      buildable: false
      externals:
      - spec: doxygen@1.11.0
        prefix: /collab/usr/gapps/axom/devtools/toss_4_x86_64_ib_cray/latest/doxygen-1.11.0
    llvm:
      version: [14.0.0]
      buildable: false
      externals:
      - spec: llvm@14.0.0+clang+python
        prefix: /usr/tce/packages/rocmcc/rocmcc-5.2.3-magic/llvm
    py-sphinx:
      version: [8.0.2]
      buildable: false
      externals:
      - spec: py-sphinx@8.0.2
        prefix: /collab/usr/gapps/axom/devtools/toss_4_x86_64_ib_cray/latest/python-3.12.5
    python:
      buildable: false
      externals:
      - spec: python@3.12.5
        prefix: /collab/usr/gapps/axom/devtools/toss_4_x86_64_ib_cray/latest/python-3.12.5
