// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#ifndef PRIMAL_EVAL_INTEGRAL_IMPL_HPP_
#define PRIMAL_EVAL_INTEGRAL_IMPL_HPP_

// Axom includes
#include "axom/config.hpp"  // for compile-time configuration options
#include "axom/primal.hpp"

// Use 1D Gauss-Legendre quadrature generated by MFEM if available,
//  or core/numerics/quadrature otherwise, which are less robust for large npts (> ~100)
#ifdef AXOM_USE_MFEM
  #include "mfem.hpp"
#else
  #include "axom/core/numerics/quadrature.hpp"
#endif

// C++ includes
#include <cmath>

namespace axom
{
namespace primal
{
namespace detail
{

class QuadratureRuleView
{
#ifdef AXOM_USE_MFEM
public:
  QuadratureRuleView(const mfem::IntegrationRule& rule) : m_quad_rule(rule) { }

  double node(int idx) const { return m_quad_rule.IntPoint(idx).x; }
  double weight(int idx) const { return m_quad_rule.IntPoint(idx).weight; }

private:
  const mfem::IntegrationRule& m_quad_rule;
#else
public:
  QuadratureRuleView(const axom::numerics::QuadratureRule& rule) : m_quad_rule(rule) { }

  double node(int idx) const { return m_quad_rule.node(idx); }
  double weight(int idx) const { return m_quad_rule.weight(idx); }

private:
  const axom::numerics::QuadratureRule& m_quad_rule;
#endif
};

/*!
 * \brief Evaluate a scalar field line integral on a single Bezier curve.
 *
 * Evaluate the scalar field line integral with MFEM integration rule if available, 
 *  or axom/numerics/quadrature otherwise, which are less robust for large npts (> ~100)
 *
 * \param [in] c the Bezier curve object
 * \param [in] integrand the lambda function representing the integrand. 
 * Must accept a 2D point as input and return a double
 * \param [in] npts The number of quadrature points in the rule
 * \return the value of the integral
 */
template <class Lambda, typename T, int NDIMS>
inline double evaluate_scalar_line_integral_component(const primal::BezierCurve<T, NDIMS>& c,
                                                      Lambda&& scalar_integrand,
                                                      const int npts)
{
#ifdef AXOM_USE_MFEM
  static mfem::IntegrationRules my_IntRules(0, mfem::Quadrature1D::GaussLegendre);
  QuadratureRuleView quad(my_IntRules.Get(mfem::Geometry::SEGMENT, 2 * npts - 1));
#else
  SLIC_WARNING_IF(npts > 100, "Axom's Gauss-Legendre nodes may be less precise for n > 100");
  QuadratureRuleView quad(axom::numerics::get_gauss_legendre(npts));
#endif

  // Store/compute quadrature result
  double full_quadrature = 0.0;
  for(int q = 0; q < npts; q++)
  {
    // Get intermediate quadrature point
    //  at which to evaluate tangent vector
    auto x_q = c.evaluate(quad.node(q));
    auto dx_q = c.dt(quad.node(q));

    full_quadrature += quad.weight(q) * scalar_integrand(x_q) * dx_q.norm();
  }

  return full_quadrature;
}

/*!
 * \brief Evaluate a vector field line integral on a single Bezier curve.
 *
 * Evaluate the vector field line integral with MFEM integration rule if available, 
 *  or axom/numerics/quadrature otherwise, which are less robust for large npts (> ~100)
 *
 * \param [in] c the Bezier curve object
 * \param [in] integrand the lambda function representing the integrand. 
 * Must accept a 2D point as input and return a 2D axom vector object
 * \param [in] npts The number of quadrature points in the rule
 * \return the value of the integral
 */
template <class Lambda, typename T, int NDIMS>
inline double evaluate_vector_line_integral_component(const primal::BezierCurve<T, NDIMS>& c,
                                                      Lambda&& vec_field,
                                                      const int npts)
{
#ifdef AXOM_USE_MFEM
  static mfem::IntegrationRules my_IntRules(0, mfem::Quadrature1D::GaussLegendre);
  QuadratureRuleView quad(my_IntRules.Get(mfem::Geometry::SEGMENT, 2 * npts - 1));
#else
  SLIC_WARNING_IF(npts > 100, "Axom's Gauss-Legendre nodes may be less precise for n > 100");
  QuadratureRuleView quad(axom::numerics::get_gauss_legendre(npts));
#endif

  // Store/compute quadrature result
  double full_quadrature = 0.0;
  for(int q = 0; q < npts; q++)
  {
    // Get intermediate quadrature point
    //  on which to evaluate dot product
    auto x_q = c.evaluate(quad.node(q));
    auto dx_q = c.dt(quad.node(q));
    auto func_val = vec_field(x_q);

    full_quadrature += quad.weight(q) * Vector<T, NDIMS>::dot_product(func_val, dx_q);
  }
  return full_quadrature;
}

/*!
 * \brief Evaluate the area integral across one component of the curved polygon.
 *
 * Intended to be called for each BezierCurve object in a curved polygon.
 * Uses a Spectral Mesh-Free Quadrature derived from Green's theorem, evaluating
 * the area integral as a line integral of the antiderivative over the curve.
 * For algorithm details, see "Spectral Mesh-Free Quadrature for Planar 
 * Regions Bounded by Rational Parametric Curves" by David Gunderman et al.
 * 
 * \param [in] cs the array of Bezier curve objects that bound the region
 * \param [in] integrand the lambda function representing the integrand. 
 * Must accept a 2D point as input and return a double
 * \param [in] The lower bound of integration for the antiderivatives
 * \param [in] npts_Q The number of quadrature points for the line integral
 * \param [in] npts_P The number of quadrature points for the antiderivative
 * \return the value of the integral, which is mathematically meaningless.
 */
template <class Lambda, typename T>
double evaluate_area_integral_component(const primal::BezierCurve<T, 2>& c,
                                        Lambda&& integrand,
                                        double int_lb,
                                        const int npts_Q,
                                        const int npts_P)
{
#ifdef AXOM_USE_MFEM
  static mfem::IntegrationRules my_IntRules(0, mfem::Quadrature1D::GaussLegendre);
  QuadratureRuleView quad_Q(my_IntRules.Get(mfem::Geometry::SEGMENT, 2 * npts_Q - 1));
  QuadratureRuleView quad_P(my_IntRules.Get(mfem::Geometry::SEGMENT, 2 * npts_P - 1));
#else
  SLIC_WARNING_IF(npts_Q > 100 || npts_P > 100,
                  "Axom's Gauss-Legendre nodes may be less precise for n > 100");
  QuadratureRuleView quad_Q(axom::numerics::get_gauss_legendre(npts_Q));
  QuadratureRuleView quad_P(axom::numerics::get_gauss_legendre(npts_P));
#endif

  // Store some intermediate values
  double antiderivative = 0.0;

  // Store/compute quadrature result
  double full_quadrature = 0.0;
  for(int q = 0; q < npts_Q; q++)
  {
    // Get intermediate quadrature point
    //  on which to evaluate antiderivative
    auto x_q = c.evaluate(quad_Q.node(q));

    // Evaluate the antiderivative at x_q, add it to full quadrature
    for(int xi = 0; xi < npts_P; xi++)
    {
      // Define interior quadrature points
      auto x_qxi = Point2D({x_q[0], (x_q[1] - int_lb) * quad_P.node(xi) + int_lb});

      antiderivative = quad_P.weight(xi) * (x_q[1] - int_lb) * integrand(x_qxi);

      full_quadrature += quad_Q.weight(q) * c.dt(quad_Q.node(q))[0] * -antiderivative;
    }
  }

  return full_quadrature;
}

}  // end namespace detail
}  // end namespace primal
}  // end namespace axom

#endif