# Copyright (c) Lawrence Livermore National Security, LLC and other
# Axom Project Contributors. See top-level LICENSE and COPYRIGHT
# files for dates and other details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

"""Helpers for locating Axom Python wheel configuration files.

The files these helpers point at (``axom-python-host-config.cmake`` and ``axom-python-env.sh``)
are generated by the pip/uv wheel build in ``src/python``.
Axom's in-tree CMake build installs the same ``axom`` package but does not generate them,
so on such an installation the accessors below raise :class:`FileNotFoundError`
rather than returning a path that does not exist.
Use :func:`has_wheel_config` to test without raising.
"""

from __future__ import annotations

import argparse
import sys
from importlib import resources
from pathlib import Path

_MISSING_HINT = (
    "This is expected for an Axom installed by its CMake build: the host-config "
    "and environment script are generated only by the pip/uv wheel build in "
    "src/python. Reinstall with `pip install <axom>/src/python` to get them."
)


def share_dir() -> Path:
    """Return the installed Axom Python package share directory.

    The directory is not required to exist; see :func:`has_wheel_config`.
    """
    return Path(resources.files("axom").joinpath("share"))


def has_wheel_config() -> bool:
    """Return True when the wheel-generated configuration files are present."""
    return (share_dir() / "axom-python-host-config.cmake").is_file()


def _require(path: Path, what: str) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"{what} not found at {path}. {_MISSING_HINT}")
    return path


def host_config_path() -> Path:
    """Return the CMake host-config generated for this Axom Python wheel.

    :raises FileNotFoundError: if this installation carries no generated host-config.
    """
    return _require(share_dir() / "axom-python-host-config.cmake", "Axom Python host-config")


def env_script_path() -> Path:
    """Return the shell environment helper generated for this Axom Python wheel.

    :raises FileNotFoundError: if this installation carries no generated env script.
    """
    return _require(share_dir() / "axom-python-env.sh", "Axom Python environment script")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Print Axom Python wheel configuration paths.")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--host-config", action="store_true", help="print the CMake host-config path")
    group.add_argument("--env-script", action="store_true", help="print the shell environment script path")
    group.add_argument("--share-dir", action="store_true", help="print the Axom Python share directory")
    group.add_argument("--cmake-args", action="store_true", help="print CMake arguments using the host-config")
    args = parser.parse_args(argv)

    try:
        if args.env_script:
            print(env_script_path())
        elif args.share_dir:
            print(share_dir())
        elif args.cmake_args:
            print(f"-C {host_config_path()}")
        else:
            print(host_config_path())
    except FileNotFoundError as err:
        print(err, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
