# Please add configuration options here.
# This provides a central location to check options and their defaults and ensure
# these are declared at the top of the cmake configuration.
#
# ENABLE_<component> options are automatically generated by the add_component macro

option(ENABLE_SHARED_LIBS "Enables shared libraries." OFF)
option(ENABLE_DOCS "Enables documentation" ON)
option(ENABLE_EXAMPLES "Enables examples" ON)
option(ENABLE_TESTS "Enables tests" ON)
option(ENABLE_CODECOV "Enables code coverage via gcov." OFF)
option(ENABLE_CXX11 "Enables C++11 language support." ON)
option(ENABLE_BOOST "Enables Boost" OFF)
option(ENABLE_FORTRAN "Enables Fortran compiler support." ON)
option(ENABLE_ALL_WARNINGS "Enables all compiler warnings on all build targets." ON)
option(ENABLE_WARNINGS_AS_ERRORS "Enables treating compiler warnings as errors on all build targets." OFF)
option(ENABLE_MPI "Enables MPI compiler support" OFF)
option(ENABLE_OPENMP "Enables OpenMP compiler support" OFF)
option(ENABLE_BENCHMARKS "Enables google benchmark" OFF)
option(ENABLE_PYTHON "Enables python use." ON)
option(ENABLE_CFORTRAN_API "Enables Fortran interface for components." ON)
