#
# This file lists the package versions for axom's dependencies
#

packages:
  adiak:
    require: 
      - spec: "@0.4.0"
  # Newer commit than 2.14.0 that fixes rocprofiler dependency
  caliper:
    require:
       - spec: "@git.7e5b7a5c0eacc077f9b842abf41c9fc7b996ce0c=master"
  # v2025.12
  camp:
    require:
      - spec: "@git.a8caefa9f4c811b1a114b4ed2c9b681d40f12325=main"
  conduit:
    require:
      - spec: "@0.9.5"
  hypre:
    require:
      - spec: "@2.27.0"
  mfem:
    require:
      - spec: "@4.9"
  opencascade:
    require:
      - spec: "@7.8.1"
  py-jsonschema:
    require:
      - spec: "@:4.17" #Anything after this requires py-rpds which requires rust and adds 40 minutes
  # v2025.12.1
  raja:
    require:
      - spec: "@git.3b8b59a1e9be2e1066c0d77372b3bf5956e6d6e2=develop"
  scr:
    require:
      - spec: "@3.0.1"
  umpire:
    require:
      - spec: "@2025.12.0"
