#
# Makefile.lt
#
BasBin = /home/taylor16/trunk/basis/dev/sgnu/bin

LOCALBUILD = /home/taylor16/testzzz-ets-4.6.3-4.3f3

# Python 3
Python = $(LOCALBUILD)/bin/python3
PythonInc = $(LOCALBUILD)/include/python3.4m
PythonLib = $(LOCALBUILD)/lib/python3.4/config-3.4m
NumPyInc = $(LOCALBUILD)/lib/python3.4/site-packages/numpy/core/include/
PYLIBS = -Wl,--export-dynamic \
	-L$(PythonLib) -lpython3.4m -ldl -lpthread -lutil


# Python source
PY_SRC = ..
# Datastore source
DS_SRC = ../..
VPATH = $(PY_SRC):$(DS_SRC)

LIBOBJS = \
	DataObject.o \
	DataGroup.o \
	DatastoreInterface.o \
	DataFunctionCompiled.o \
	c-datastore.o

PYOBJS = \
	dsmodule.o \
	DataFunctionPython.o

CLIBS =  -L. -lds -lstdc++
CXXLIBS = -L. -lds $(PYLIBS)

CFLAGS = -fPIC -O0 -g3 -std=c99 -I$(DS_SRC)
CXXFLAGS = -fPIC -O0 -g3 -std=c++11 -Wall -Wextra -Wshadow -pedantic -Woverloaded-virtual -Wno-unused-variable -Wno-unused-parameter -Wno-return-type -I. -I.. -I$(DS_SRC) -I$(PythonInc) -I$(NumPyInc) -fpermissive
# -Wabi

all : sim.x datastore.so

$(LIBOBJS) : Attributes.hpp DataGroup.hpp Types.hpp DataFunctionCompiled.hpp DataObject.hpp Utilities.hpp DataFunction.hpp DatastoreInterface.hpp

libds.a : $(LIBOBJS)
	ar -rsc $@ $?

libpyds.a : $(PYOBJS)
	ar -rsc $@ $?

datastore.so : $(LIBOBJS) $(PYOBJS)
	$(CXX) -shared -o $@ $^

sim.x : $(LIBOBJS) $(PYOBJS) dstestmodule.o

../dsmodule.cpp : ../ds.yaml
	(cd ..; $(BasBin)/modulator2 ds.yaml)

dstestmodule.cpp : dstest.yaml
	$(BasBin)/modulator2 dstest.yaml

#DataGroup.o : $(DS_SRC)/DataGroup.cpp
%.o : %.cpp
	$(CXX) $(CXXFLAGS) $< -c -o $@

%.x : %.c
	$(CC) $(CFLAGS) -I$(DS_SRC) $^ $(CLIBS) -o $@

%.x : %.cpp
	$(CXX) $(CXXFLAGS) -I$(DS_SRC) $^ $(CXXLIBS) -o $@

clean : 
	rm -f *~ test*.x libds.a $(LIBOBJS) libpyds.a ds.so $(PYOBJS)

.PHONY : clean

