// wrapSidre.h
// This file is generated by Shroud 0.12.2. Do not edit.
//
// Copyright (c) 2017-2021, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
/**
 * \file wrapSidre.h
 * \brief Shroud generated wrapper for sidre namespace
 */
// For C users and C++ implementation

#ifndef WRAPSIDRE_H
#define WRAPSIDRE_H

#include "typesSidre.h"
#ifndef __cplusplus
  #include <stdbool.h>
#endif

// splicer begin CXX_declarations
// splicer end CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin C_declarations
// splicer end C_declarations

bool SIDRE_name_is_valid(const char* name);

#ifdef __cplusplus
}
#endif

#endif  // WRAPSIDRE_H
