#
# Generate the API files
#
# TODO: replace with CMake targets Jira ATK-137

gen : api.yaml
	echo "shroud api.yaml"
	(chmod 755 $(HOME)/datastore/sprint3/build-debug/bin/shroud ; \
	$(HOME)/datastore/sprint3/build-debug/bin/shroud api.yaml)
