// Copyright (c) 2017-2022, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

/*!
 * \file quest_distributed_distance_query_example.cpp
 * \brief Driver for a distributed distance query
 */

// Axom includes
#include "axom/config.hpp"
#include "axom/core.hpp"
#include "axom/slic.hpp"
#include "axom/primal.hpp"
#include "axom/sidre.hpp"
#include "axom/quest.hpp"
#include "axom/slam.hpp"
#include "axom/core/Types.hpp"
#include "axom/core/utilities/WhereMacro.hpp"

#include "conduit_blueprint.hpp"
#include "conduit_blueprint_mpi.hpp"

#include "axom/quest/DistributedClosestPoint.hpp"

#include "axom/fmt.hpp"
#include "axom/CLI11.hpp"

#ifndef AXOM_USE_MFEM
  #error This example requires Axom to be configured with MFEM and the AXOM_ENABLE_MFEM_SIDRE_DATACOLLECTION option
#endif
#include "mfem.hpp"

#ifndef AXOM_USE_MPI
  #error This example requires Axom to be configured with MPI
#endif
#include "mpi.h"

// C/C++ includes
#include <string>
#include <limits>
#include <map>
#include <vector>
#include <cmath>

namespace quest = axom::quest;
namespace slic = axom::slic;
namespace sidre = axom::sidre;
namespace slam = axom::slam;
namespace spin = axom::spin;
namespace primal = axom::primal;
namespace mint = axom::mint;
namespace numerics = axom::numerics;

using RuntimePolicy = axom::quest::DistributedClosestPoint::RuntimePolicy;

// converts the input string into an 80 character string
// padded on both sides with '=' symbols
std::string banner(const std::string& str)
{
  return axom::fmt::format("{:=^80}", str);
}

/// Struct to parse and store the input parameters
struct Input
{
public:
  std::string meshFile;
  std::string distanceFile {"cp_coords"};
  std::string objectFile {"object_mesh"};

  double circleRadius {1.0};
  std::vector<double> circleCenter {0.0, 0.0};
  // TODO: Ensure that circleCenter size matches dimensionality.
  int circlePoints {100};
  RuntimePolicy policy {RuntimePolicy::seq};

  double distThreshold {std::numeric_limits<double>::max()};

  bool checkResults {false};

  bool randomSpacing {true};

  unsigned int minDomainCount {1};
  unsigned int maxDomainCount {1};

private:
  bool m_verboseOutput {false};
  double m_emptyRankProbability {0.};

  // clang-format off
  const std::map<std::string, RuntimePolicy> s_validPolicies
  {
      {"seq", RuntimePolicy::seq}
#if defined(AXOM_USE_RAJA) && defined(AXOM_USE_UMPIRE)
  #ifdef AXOM_USE_OPENMP
    , {"omp", RuntimePolicy::omp}
  #endif
  #ifdef AXOM_USE_CUDA
    , {"cuda", RuntimePolicy::cuda}
  #endif
  #ifdef AXOM_USE_HIP
    , {"hip", RuntimePolicy::hip}
  #endif
#endif
  };
  // clang-format on

public:
  bool isVerbose() const { return m_verboseOutput; }
  double percentEmptyRanks() const { return m_emptyRankProbability; }

  std::string getDCMeshName() const
  {
    using axom::utilities::string::removeSuffix;

    // Remove the parent directories and file suffix
    std::string name = axom::Path(meshFile).baseName();
    name = removeSuffix(name, ".root");

    return name;
  }

  void parse(int argc, char** argv, axom::CLI::App& app)
  {
    app.add_option("-m,--mesh-file", meshFile)
      ->description(
        "Path to computational mesh (generated by MFEMSidreDataCollection)")
      ->check(axom::CLI::ExistingFile)
      ->required();

    app.add_option("-s,--distance-file", distanceFile)
      ->description("Name of output mesh file containing closest distance.")
      ->capture_default_str();

    app.add_option("-o,--object-file", objectFile)
      ->description("Name of output file containing object mesh.")
      ->capture_default_str();

    app.add_flag("-v,--verbose,!--no-verbose", m_verboseOutput)
      ->description("Enable/disable verbose output")
      ->capture_default_str();

    app.add_option("--empty-rank-probability", m_emptyRankProbability)
      ->description(
        "Probability that a rank's data is empty "
        "(tests code's ability to handle empty ranks)")
      ->check(axom::CLI::Range(0., 1.))
      ->capture_default_str();

    app.add_option("--min-domain-count", minDomainCount)
      ->description(
        "Min number of domains per rank."
        "Defaults to 1")
      ->check(axom::CLI::Range(0, 10))
      ->capture_default_str();

    // TODO: Any way to set min and max together and require max >= min?
    app.add_option("--max-domain-count", maxDomainCount)
      ->description(
        "Max number of domains per rank."
        "Defaults to 1")
      ->check(axom::CLI::Range(0, 10))
      ->capture_default_str();

    app.add_option("-r,--radius", circleRadius)
      ->description("Radius for circle")
      ->capture_default_str();

    auto* circle_options =
      app.add_option_group("circle",
                           "Options for setting up the circle of points");
    circle_options->add_option("--center", circleCenter)
      ->description("Center for object (x,y[,z])")
      ->expected(2, 3);

    app.add_flag("--random-spacing,!--no-random-spacing", randomSpacing)
      ->description("Enable/disable random spacing of circle points")
      ->capture_default_str();

    app.add_option("-d,--dist-threshold", distThreshold)
      ->check(axom::CLI::NonNegativeNumber)
      ->description("Distance threshold to search")
      ->capture_default_str();

    app.add_option("-n,--num-samples", circlePoints)
      ->description("Number of points for circle")
      ->capture_default_str();

    app.add_option("-p, --policy", policy)
      ->description("Set runtime policy for point query method")
      ->capture_default_str()
      ->transform(axom::CLI::CheckedTransformer(s_validPolicies));

    app.add_flag("-c,--check-results,!--no-check-results", checkResults)
      ->description(
        "Enable/disable checking results against analytical solution")
      ->capture_default_str();

    app.get_formatter()->column_width(60);

    // could throw an exception
    app.parse(argc, argv);

    slic::setLoggingMsgLevel(m_verboseOutput ? slic::message::Debug
                                             : slic::message::Info);
  }
};

/**
 *  \brief Simple wrapper to a blueprint particle mesh
 *
 *  Given a sidre Group, creates the stubs for a mesh blueptint particle mesh
 */
struct BlueprintParticleMesh
{
public:
  explicit BlueprintParticleMesh(sidre::Group* group = nullptr,
                                 const std::string& coordset = "coords",
                                 const std::string& topology = "mesh")
    : m_coordsetName(coordset)
    , m_topologyName(topology)
    , m_group(group)
    , m_domainGroups()
  {
    MPI_Comm_rank(MPI_COMM_WORLD, &m_rank);
    MPI_Comm_size(MPI_COMM_WORLD, &m_nranks);
  }

  /// Gets the root group for this mesh blueprint
  sidre::Group* rootGroup() const { return m_group; }
  /// Gets a domain group.
  sidre::Group* domainGroup(axom::IndexType groupIdx) const
  {
    SLIC_ASSERT(size_t(groupIdx) < m_domainGroups.size());
    return m_domainGroups[groupIdx];
  }
  /// Gets the parent group for the blueprint coordinate set
  sidre::Group* coordsGroup(axom::IndexType groupIdx) const { return m_coordsGroups[groupIdx]; }
  /// Gets the parent group for the blueprint mesh topology
  sidre::Group* topoGroup(axom::IndexType groupIdx) const { return m_topoGroups[groupIdx]; }

  const std::string& getCoordsetName() const { return m_coordsetName; }

  /// Gets the MPI rank for this mesh
  int getRank() const { return m_rank; }
  /// Gets the number of ranks in the problem
  int getNumRanks() const { return m_nranks; }

  /// Returns true if points have been added to the particle mesh
  bool hasPoints() const
  {
    // return m_coordsGroup != nullptr && m_coordsGroup->hasView("values/x");
    for(auto *cg : m_coordsGroups)
    {
      if(cg != nullptr && cg->hasView("values/x")) return true;
    }
    return false;
  }

  /// Returns the number of points in the particle mesh
  int numPoints() const
  {
    // return hasPoints() ? m_coordsGroup->getView("values/x")->getNumElements() : 0;
    int rval = 0;
    for(auto *cg : m_coordsGroups)
    {
      if(cg != nullptr && cg->hasView("values/x"))
      {
        rval += cg->getView("values/x")->getNumElements();
      }
    }
    return rval;
  }

  int dimension() const { return m_dimension; }

  /// Set the coordinate data from an array of primal Points, templated on the dimension
  // The points are assigned to a new domain (in the multidomain context).
  template <int NDIMS>
  void setPoints(const axom::Array<primal::Point<double, NDIMS>>& pts)
  {
    axom::IndexType domainIdx = createBlueprintStubs();
    SLIC_ASSERT(m_domainGroups[domainIdx] != nullptr);

    const int SZ = pts.size();

    m_dimension = NDIMS;

    // lamda to create a strided view into the buffer
    // uses workaround for empty meshes since apply() requires size > 0
    auto createAndApplyView = [=](sidre::Group* grp,
                                  const std::string& path,
                                  sidre::Buffer* buf,
                                  int dim,
                                  int sz) {
      if(sz > 0)
      {
        grp->createView(path)->attachBuffer(buf)->apply(sz, dim, NDIMS);
      }
      else
      {
        grp->createViewAndAllocate(path, sidre::DOUBLE_ID, 0);
      }
    };

    // create views into a shared buffer for the coordinates, with stride NDIMS
    {
      auto* buf = m_domainGroups[domainIdx]->getDataStore()
                    ->createBuffer(sidre::DOUBLE_ID, NDIMS * SZ)
                    ->allocate();

      createAndApplyView(m_coordsGroups[domainIdx], "values/x", buf, 0, SZ);
      if(NDIMS > 1)
      {
        createAndApplyView(m_coordsGroups[domainIdx], "values/y", buf, 1, SZ);
      }
      if(NDIMS > 2)
      {
        createAndApplyView(m_coordsGroups[domainIdx], "values/z", buf, 2, SZ);
      }

      // copy coordinate data into the buffer
      const std::size_t nbytes = sizeof(double) * SZ * NDIMS;
      axom::copy(buf->getVoidPtr(), pts.data(), nbytes);
    }

    // set the default connectivity
    sidre::Array<int> arr(m_topoGroups[domainIdx]->createView("elements/connectivity"), SZ, SZ);
    for(int i = 0; i < SZ; ++i)
    {
      arr[i] = i;
    }
  }

  template <typename T>
  void registerNodalScalarField(const std::string& fieldName)
  {
    SLIC_ASSERT_MSG(hasPoints(),
                    "Cannot register a field with the BlueprintParticleMesh "
                    "before adding points");

    auto* fld = m_fieldsGroups[0]->createGroup(fieldName);
    fld->createViewString("association", "vertex");
    fld->createViewString("topology", m_topoGroups[0]->getName());
    fld->createViewAndAllocate("values",
                               sidre::detail::SidreTT<T>::id,
                               numPoints());
  }

  template <typename T>
  void registerNodalVectorField(const std::string& fieldName)
  {
    SLIC_ASSERT_MSG(hasPoints(),
                    "Cannot register a field with the BlueprintParticleMesh "
                    "before adding points");

    const int SZ = numPoints();
    const int DIM = dimension();

    auto* fld = m_fieldsGroups[0]->createGroup(fieldName);
    fld->createViewString("association", "vertex");
    fld->createViewString("topology", m_topoGroups[0]->getName());

    // create views into a shared buffer for the coordinates, with stride NDIMS
    auto* buf = m_domainGroups[0]->getDataStore()
                  ->createBuffer(sidre::detail::SidreTT<T>::id, DIM * SZ)
                  ->allocate();
    switch(DIM)
    {
    case 3:
      fld->createView("values/x")->attachBuffer(buf)->apply(SZ, 0, DIM);
      fld->createView("values/y")->attachBuffer(buf)->apply(SZ, 1, DIM);
      fld->createView("values/z")->attachBuffer(buf)->apply(SZ, 2, DIM);
      break;
    case 2:
      fld->createView("values/x")->attachBuffer(buf)->apply(SZ, 0, DIM);
      fld->createView("values/y")->attachBuffer(buf)->apply(SZ, 1, DIM);
      break;
    default:
      fld->createView("values/x")->attachBuffer(buf)->apply(SZ, 0, DIM);
      break;
    }
  }

  bool hasField(const std::string& fieldName) const
  {
    return m_fieldsGroups[0]->hasGroup(fieldName);
  }

  template <typename T>
  axom::ArrayView<T> getNodalScalarField(const std::string& fieldName) const
  {
    SLIC_ASSERT_MSG(hasPoints(),
                    "Cannot extract a field from the BlueprintParticleMesh "
                    "before adding points");

    T* data = hasField(fieldName)
      ? static_cast<T*>(
          m_fieldsGroups[0]->getView(axom::fmt::format("{}/values", fieldName))
            ->getVoidPtr())
      : nullptr;

    return axom::ArrayView<T>(data, numPoints());
  }

  template <typename T>
  axom::ArrayView<T> getNodalVectorField(const std::string& fieldName) const
  {
    SLIC_ASSERT_MSG(hasPoints(),
                    "Cannot extract a field from the BlueprintParticleMesh "
                    "before adding points");

    // Note: the implementation currently assumes that the field data is
    // interleaved, so it is safe to get a pointer to the beginning of the
    // x-coordinate's data. This will be relaxed in the future, and we will
    // need to modify this implementation accordingly.
    T* data = hasField(fieldName)
      ? static_cast<T*>(
          m_fieldsGroups[0]->getView(axom::fmt::format("{}/values/x", fieldName))
            ->getVoidPtr())
      : nullptr;

    return axom::ArrayView<T>(data, numPoints());
  }

  /// Checks whether the blueprint is valid and prints diagnostics
  bool isValid() const
  {
#if 1
    {
      conduit::Node meshNode;
      m_group->createNativeLayout(meshNode);
      conduit::Node info;
      if(!conduit::blueprint::mpi::verify("mesh", meshNode, info, MPI_COMM_WORLD))
      {
        SLIC_INFO("Invalid blueprint for particle mesh: \n" << info.to_yaml());
        return false;
      }
      // info.print();
    }
    return true;
#else
    // This is old.  It only checks the first child node.
    conduit::Node mesh_node;

    // use an empty conduit node for meshes with 0 elements
    if(numPoints() > 0)
    {
      m_domainGroups[0]->createNativeLayout(mesh_node);
    }

    bool success = true;
    conduit::Node info;
    if(!conduit::blueprint::mpi::verify("mesh", mesh_node, info, MPI_COMM_WORLD))
    {
      SLIC_INFO("Invalid blueprint for particle mesh: \n" << info.to_yaml());
      success = false;
    }

    return success;
#endif
  }

  /// Outputs the particle mesh to disk
  void saveMesh(const std::string& outputMesh)
  {
    auto* ds = m_group->getDataStore();
    sidre::IOManager writer(MPI_COMM_WORLD);
    writer.write(ds->getRoot(), m_nranks, outputMesh, "sidre_hdf5");

    MPI_Barrier(MPI_COMM_WORLD);

    // m_group->print();
    // Add the bp index to the root file
    writer.writeBlueprintIndexToRootFile(ds,
                                         m_group->getName(),
                                         outputMesh + ".root",
                                         "object_mesh"); // m_domainGroups[0]->getPathName());
  }

private:
  /// Creates blueprint stubs for this mesh
  // for the "coordset", "topologies", "fields" and "state"
  // Return the domain index created.
  axom::IndexType createBlueprintStubs()
  {
    SLIC_ASSERT(m_group != nullptr);

    auto* domainGroup = m_group->createUnnamedGroup();

    auto *coordsGroup = domainGroup->createGroup("coordsets")->createGroup(m_coordsetName);
    coordsGroup->createViewString("type", "explicit");
    coordsGroup->createGroup("values");

    auto *topoGroup = domainGroup->createGroup("topologies")->createGroup(m_topologyName);
    topoGroup->createViewString("coordset", m_coordsetName);
    topoGroup->createViewString("type", "unstructured");
    topoGroup->createViewString("elements/shape", "point");

    auto *fieldsGroup = domainGroup->createGroup("fields");

    domainGroup->createViewScalar<axom::int64>("state/domain_id", m_rank);

    m_domainGroups.push_back(domainGroup);
    m_coordsGroups.push_back(coordsGroup);
    m_topoGroups.push_back(topoGroup);
    m_fieldsGroups.push_back(fieldsGroup);

    return axom::IndexType(m_domainGroups.size() - 1);
  }

private:
  const std::string m_coordsetName;
  const std::string m_topologyName;
  /// Parent group for the entire mesh
  sidre::Group* m_group;
  /// Group for each domain in multidomain mesh
  std::vector<sidre::Group*> m_domainGroups;

  std::vector<sidre::Group*> m_coordsGroups;
  std::vector<sidre::Group*> m_topoGroups;
  std::vector<sidre::Group*> m_fieldsGroups;

  int m_rank;
  int m_nranks;
  int m_dimension {-1};
};  // BlueprintParticleMesh

/**
 * Helper class to generate a mesh blueprint-conforming particle mesh for the input object.
 * The mesh is represented using a Sidre hierarchy
 */
class ObjectMeshWrapper
{
public:
  using Circle = primal::Sphere<double, 2>;

  ObjectMeshWrapper(sidre::Group* group) : m_objectMesh(group)
  {
    SLIC_ASSERT(group != nullptr);
  }

  /// Get a pointer to the root group for this mesh
  sidre::Group* getBlueprintGroup() const { return m_objectMesh.rootGroup(); }

  std::string getCoordsetName() const
  {
    return m_objectMesh.getCoordsetName();
  }

  int numPoints() const { return m_objectMesh.numPoints(); }

  void setVerbosity(bool verbose) { m_verbose = verbose; }

  /**
   * Generates a collection of \a numPoints points along a circle.
   * Point spacing can be random (default) or uniform.
   */
  void generateCircleMesh(const Circle& circle,
                          int totalNumPoints,
                          int localDomainCount,
                          bool randomSpacing = true)
  {
    using axom::utilities::random_real;

    constexpr int DIM = 2;
    using PointType = primal::Point<double, DIM>;
    using PointArray = axom::Array<PointType>;

    int rank = m_objectMesh.getRank();
    int nranks = m_objectMesh.getNumRanks();

    // perform scan on ranks to compute totalNumPoints, thetaStart and thetaEnd
    axom::Array<int> sums(nranks, nranks);
    {
      axom::Array<int> indivDomainCounts(nranks, nranks);
      indivDomainCounts.fill(-1);
      MPI_Allgather(&localDomainCount, 1, MPI_INT, indivDomainCounts.data(), 1,
                    MPI_INT, MPI_COMM_WORLD);

      SLIC_DEBUG_IF(
        m_verbose,
        axom::fmt::format("After all gather: [{}]", axom::fmt::join(indivDomainCounts, ",")));

      sums[0] = indivDomainCounts[0];
      for(int i = 1; i < nranks; ++i)
      {
        sums[i] = sums[i - 1] + indivDomainCounts[i];
      }
      // If no rank has any domains, force last one to 1 domain.
      if(sums[nranks - 1] == 0)
      {
        sums[nranks - 1] = 1;
        if(rank == nranks - 1)
        {
          localDomainCount = 1;
        }
      }
    }

    SLIC_DEBUG_IF(
      m_verbose,
      axom::fmt::format("After scan: [{}]", axom::fmt::join(sums, ",")));

    int globalDomainCount = sums[nranks - 1];
    totalNumPoints = std::max(totalNumPoints, globalDomainCount);
    int ptsPerDomain = totalNumPoints / globalDomainCount;
    int domainsWithExtraPt = totalNumPoints % globalDomainCount;

    int myDomainBegin = rank == 0 ? 0 : sums[rank - 1];
    int myDomainEnd = sums[rank];
    assert(myDomainEnd-myDomainBegin == localDomainCount);

    double radius = circle.getRadius();
    const auto& center = circle.getCenter();
    const double avgAng = 2. * M_PI / totalNumPoints;

    for(int di=myDomainBegin; di<myDomainEnd; ++di)
    {
      int pBegin = di * ptsPerDomain + std::min(di, domainsWithExtraPt);
      int pEnd =
        (di + 1) * ptsPerDomain + std::min((di + 1), domainsWithExtraPt);
      int domainPointCount = pEnd - pBegin;
      PointArray pts(0, domainPointCount);

      for(int pi = pBegin; pi < pEnd; ++pi)
      {
        const double ang = randomSpacing
          ? random_real(avgAng * pBegin, avgAng * pEnd)
          : pi * avgAng;
        const double rsinT = center[1] + radius * std::sin(ang);
        const double rcosT = center[0] + radius * std::cos(ang);
        pts.push_back(PointType {rcosT, rsinT});
      }
      m_objectMesh.setPoints(pts);
std::cout<<__WHERE<< "rank " << rank << " got " << pts.size() << " circle points from domain (global index) " << di << std::endl;
    }

    axom::slic::flushStreams();
    SLIC_ASSERT(m_objectMesh.isValid());
  }

  /// Outputs the object mesh to disk
  void saveMesh(const std::string& outputMesh = "object_mesh")
  {
    SLIC_INFO(banner(
      axom::fmt::format("Saving particle mesh '{}' to disk", outputMesh)));

    m_objectMesh.saveMesh(outputMesh);
  }

private:
  BlueprintParticleMesh m_objectMesh;
  bool m_verbose {false};
};

class QueryMeshWrapper
{
public:
  using Circle = primal::Sphere<double, 2>;

  QueryMeshWrapper(const std::string& cpFilename,
                   const std::string& dcMeshFilename,
                   const std::string& dcMeshPath)
    : m_dc(cpFilename, nullptr, true)
    , m_queryMesh(m_dc.GetBPGroup()->getDataStore()->getRoot()
                  ->createGroup("query_mesh", true))
  {
    setupMesh(dcMeshFilename, dcMeshPath);
    setupParticleMesh();
  }

  // Returns a pointer to the MFEMSidreDataCollection
  sidre::MFEMSidreDataCollection* getDC() { return &m_dc; }
  const sidre::MFEMSidreDataCollection* getDC() const { return &m_dc; }

  const BlueprintParticleMesh& getParticleMesh() const { return m_queryMesh; }

  sidre::Group* getBlueprintGroup() const { return m_queryMesh.rootGroup(); }

  std::string getCoordsetName() const
  {
    return m_queryMesh.getCoordsetName();
  }

  /// Returns an array containing the positions of the mesh vertices
  template <typename PointArray>
  PointArray getVertexPositions()
  {
    auto* mesh = m_dc.GetMesh();
    const int NV = mesh->GetNV();
    PointArray arr(NV);

    for(auto i : slam::PositionSet<int>(NV))
    {
      mesh->GetNode(i, arr[i].data());
    }

    return arr;
  }

  /// Saves the data collection (MFEM query mesh) to disk
  void saveMesh()
  {
    SLIC_INFO(banner(axom::fmt::format("Saving query mesh '{}' to disk",
                                       m_dc.GetCollectionName())));

    m_dc.Save();
  }

  void setupParticleMesh()
  {
    using PointArray2D = axom::Array<primal::Point<double, 2>>;
    using PointArray3D = axom::Array<primal::Point<double, 3>>;

    const int DIM = m_dc.GetMesh()->Dimension();
    SLIC_ERROR_IF(DIM != 2 && DIM != 3,
                  "Only 2D and 3D meshes are supported in setupParticleMesh(). "
                  "Attempted mesh dimension was "
                    << DIM);

    switch(DIM)
    {
    case 2:
      m_queryMesh.setPoints<2>(getVertexPositions<PointArray2D>());
      break;
    case 3:
      m_queryMesh.setPoints<3>(getVertexPositions<PointArray3D>());
      break;
    }

    m_queryMesh.registerNodalScalarField<axom::IndexType>("cp_rank");
    m_queryMesh.registerNodalScalarField<axom::IndexType>("cp_index");
    m_queryMesh.registerNodalScalarField<double>("cp_distance");
    m_queryMesh.registerNodalVectorField<double>("cp_coords");

    SLIC_ASSERT(m_queryMesh.isValid());
  }

  /**
   * Loads the mesh as an MFEMSidreDataCollection with
   * the following fields: "position", "distance", "direction"
   */
  void setupMesh(const std::string& fileName, const std::string meshFile)
  {
    SLIC_INFO(banner(axom::fmt::format("Loading '{}' mesh", fileName)));

    sidre::MFEMSidreDataCollection originalMeshDC(fileName, nullptr, false);
    {
      originalMeshDC.SetComm(MPI_COMM_WORLD);
      originalMeshDC.Load(meshFile, "sidre_hdf5");
    }
    SLIC_ASSERT_MSG(originalMeshDC.GetMesh()->Dimension() == 2,
                    "This application currently only supports 2D meshes");
    // TODO: Check order and apply LOR, if necessary

    const int DIM = originalMeshDC.GetMesh()->Dimension();

    // Create the data collection
    mfem::Mesh* cpMesh = nullptr;
    {
      m_dc.SetMeshNodesName("position");

      auto* pmesh = dynamic_cast<mfem::ParMesh*>(originalMeshDC.GetMesh());
      cpMesh = (pmesh != nullptr) ? new mfem::ParMesh(*pmesh)
                                  : new mfem::Mesh(*originalMeshDC.GetMesh());
      m_dc.SetMesh(cpMesh);
    }

    // Register the distance and direction grid function
    constexpr int order = 1;
    auto* fec = new mfem::H1_FECollection(order, DIM, mfem::BasisType::Positive);
    mfem::FiniteElementSpace* fes = new mfem::FiniteElementSpace(cpMesh, fec);
    mfem::GridFunction* distances = new mfem::GridFunction(fes);
    distances->MakeOwner(fec);
    m_dc.RegisterField("distance", distances);

    auto* vfec = new mfem::H1_FECollection(order, DIM, mfem::BasisType::Positive);
    mfem::FiniteElementSpace* vfes =
      new mfem::FiniteElementSpace(cpMesh, vfec, DIM);
    mfem::GridFunction* directions = new mfem::GridFunction(vfes);
    directions->MakeOwner(vfec);
    m_dc.RegisterField("direction", directions);

    // Register the "error_flag" grid function
    auto* efec = new mfem::H1_FECollection(order, DIM, mfem::BasisType::Positive);
    mfem::FiniteElementSpace* efes = new mfem::FiniteElementSpace(cpMesh, efec);
    mfem::GridFunction* errFlags = new mfem::GridFunction(efes);
    errFlags->MakeOwner(efec);
    m_dc.RegisterField("error_flag", errFlags);
    // Initialize errorFlag to zeroes.
    *errFlags = 0;
  }

  /// Prints some info about the mesh
  void printMeshInfo()
  {
    switch(m_dc.GetMesh()->Dimension())
    {
    case 2:
      printMeshInfo<2>();
      break;
    case 3:
      printMeshInfo<3>();
      break;
    }
  }

  /**
   * Check for error in the search.
   * - check that points within threshold have a closest point
   *   on the object.
   * - check that found closest-point is near its corresponding
   *   closest point on the circle (within tolerance)
   *
   * Return number of errors found on the local mesh partition.
   * Populate "error_flag" field with the number of errors, for
   * visualization.
   *
   * Randomized circle points (--random-spacing switch) can cause
   * false positives, so when it's on, distance inaccuracy is a warning
   * (not an error) for the purpose of checking.
   */
  template <int NDIMS>
  int checkClosestPoints(const Circle& circle, const Input& params)
  {
    using PointType = Circle::PointType;
    using PointArray = axom::Array<PointType>;
    using IndexSet = slam::PositionSet<>;

    auto queryPts = getVertexPositions<PointArray>();

    auto cpCoords =
      getParticleMesh().getNodalVectorField<PointType>("cp_coords");

    auto cpIndices =
      getParticleMesh().getNodalScalarField<axom::IndexType>("cp_index");

    SLIC_ASSERT(queryPts.size() == cpCoords.size());
    SLIC_ASSERT(queryPts.size() == cpIndices.size());

    if(params.isVerbose())
    {
      SLIC_INFO(axom::fmt::format("Closest points ({}):", cpCoords.size()));
    }

    /*
      Allowable slack is half the arclength between 2 adjacent circle
      points.  A query point on the circle can correctly have that
      closest-distance, even though the analytical distance is zero.
      If spacing is random, distance between adjacent points is not
      predictable, leading to false positives.  We don't claim errors
      for this in when using random.
    */
    const double avgObjectRes =
      2 * M_PI * params.circleRadius / params.circlePoints;
    const double allowableSlack = avgObjectRes / 2;

    int sumErrCount = 0;
    int sumWarningCount = 0;
    auto& errorFlag = *getDC()->GetField("error_flag");
    for(auto i : IndexSet(queryPts.size()))
    {
      const auto& qPt = queryPts[i];
      const auto& cpCoord = cpCoords[i];
      double analyticalDist = std::fabs(circle.computeSignedDistance(qPt));
      const bool closestPointFound = (cpIndices[i] == -1);
      if(closestPointFound)
      {
        if(analyticalDist < params.distThreshold - allowableSlack)
        {
          errorFlag[i] = true;
          SLIC_INFO(
            axom::fmt::format("***Error: Query point {} ({}) is within "
                              "threshold by {} but lacks closest point.",
                              i,
                              qPt,
                              params.distThreshold - analyticalDist));
        }
      }
      else
      {
        if(analyticalDist >= params.distThreshold + allowableSlack)
        {
          errorFlag[i] = true;
          SLIC_INFO(
            axom::fmt::format("***Error: Query point {} ({}) is outside "
                              "threshold by {} but has closest point at {}.",
                              i,
                              qPt,
                              analyticalDist - params.distThreshold,
                              cpCoord));
        }

        if(!axom::utilities::isNearlyEqual(circle.computeSignedDistance(cpCoord),
                                           0.0))
        {
          errorFlag[i] = true;
          SLIC_INFO(axom::fmt::format(
            "***Error: Closest point ({}) for index {} is not on the circle.",
            cpCoords[i],
            i));
        }

        double dist = sqrt(primal::squared_distance(qPt, cpCoord));
        if(!axom::utilities::isNearlyEqual(dist, analyticalDist, allowableSlack))
        {
          if(params.randomSpacing)
          {
            ++sumWarningCount;
            SLIC_INFO(axom::fmt::format(
              "***Warning: Closest distance for index {} is {}, off by {}.",
              i,
              dist,
              dist - analyticalDist));
          }
          else
          {
            errorFlag[i] = true;
            SLIC_INFO(
              axom::fmt::format("***Error: Closest distance for index {} is "
                                "{}, off by {}.",
                                i,
                                dist,
                                dist - analyticalDist));
          }
        }
      }
      sumErrCount += errorFlag[i];
    }

    SLIC_INFO(axom::fmt::format(
      "Local partition has {} errors, {} warnings in closest distance results.",
      sumErrCount,
      sumWarningCount));

    return sumErrCount;
  }

private:
  /**
  * \brief Print some info about the mesh
  *
  * \note In MPI-based configurations, this is a collective call, but only prints on rank 0
  */
  template <int DIM>
  void printMeshInfo()
  {
    mfem::Mesh* mesh = m_dc.GetMesh();

    int myRank = 0;
    int numElements = mesh->GetNE();

    mfem::Vector mins, maxs;

    auto* pmesh = dynamic_cast<mfem::ParMesh*>(mesh);
    if(pmesh != nullptr)
    {
      pmesh->GetBoundingBox(mins, maxs);
      numElements = pmesh->ReduceInt(numElements);
      myRank = pmesh->GetMyRank();
    }
    else
    {
      mesh->GetBoundingBox(mins, maxs);
    }

    if(myRank == 0)
    {
      SLIC_INFO(axom::fmt::format(
        "Mesh has {} elements and (approximate) bounding box {}",
        numElements,
        primal::BoundingBox<double, DIM>(
          primal::Point<double, DIM>(mins.GetData()),
          primal::Point<double, DIM>(maxs.GetData()))));
    }

    slic::flushStreams();
  }

private:
  sidre::MFEMSidreDataCollection m_dc;
  BlueprintParticleMesh m_queryMesh;
};

/// Utility function to initialize the logger
void initializeLogger()
{
  // Initialize Logger
  slic::initialize();
  slic::setLoggingMsgLevel(slic::message::Info);

  slic::LogStream* logStream;

#ifdef AXOM_USE_MPI
  std::string fmt = "[<RANK>][<LEVEL>]: <MESSAGE>\n";
  #ifdef AXOM_USE_LUMBERJACK
  const int RLIMIT = 8;
  logStream = new slic::LumberjackStream(&std::cout, MPI_COMM_WORLD, RLIMIT, fmt);
  #else
  logStream = new slic::SynchronizedStream(&std::cout, MPI_COMM_WORLD, fmt);
  #endif
#else
  std::string fmt = "[<LEVEL>]: <MESSAGE>\n";
  logStream = new slic::GenericOutputStream(&std::cout, fmt);
#endif  // AXOM_USE_MPI

  slic::addStreamToAllMsgLevels(logStream);
}

/// Utility function to finalize the logger
void finalizeLogger()
{
  if(slic::isInitialized())
  {
    slic::flushStreams();
    slic::finalize();
  }
}

//------------------------------------------------------------------------------
int main(int argc, char** argv)
{
  MPI_Init(&argc, &argv);
  int my_rank, num_ranks;
  MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
  MPI_Comm_size(MPI_COMM_WORLD, &num_ranks);

  initializeLogger();
  //slic::setAbortOnWarning(true);

  //---------------------------------------------------------------------------
  // Set up and parse command line arguments
  //---------------------------------------------------------------------------
  Input params;
  axom::CLI::App app {"Driver for distributed distance query"};

  try
  {
    params.parse(argc, argv, app);
  }
  catch(const axom::CLI::ParseError& e)
  {
    int retval = -1;
    if(my_rank == 0)
    {
      retval = app.exit(e);
    }

    MPI_Bcast(&retval, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Finalize();

    exit(retval);
  }

  // Issue warning about result-checking requiring good resolution.
  if(params.checkResults && params.randomSpacing)
  {
    SLIC_INFO(axom::fmt::format(
      "***Warning: Result-checking may yield false positive (warnings) when "
      "circle points have random spacing.  High resolution helps limit this."
      "We recommend at least 500 points for each radius length unit."));
  }

  constexpr int DIM = 2;

  using PointType = primal::Point<double, DIM>;
  using PointArray = axom::Array<PointType>;
  using IndexSet = slam::PositionSet<>;
  using Circle = primal::Sphere<double, DIM>;

  //---------------------------------------------------------------------------
  // Load/generate object mesh
  //---------------------------------------------------------------------------
  const Circle circle(
    PointType(params.circleCenter.data(), params.circleCenter.size()),
    params.circleRadius);

  sidre::DataStore objectDS;
  ObjectMeshWrapper object_mesh_wrapper(
    objectDS.getRoot()->createGroup("object_mesh", true));
  object_mesh_wrapper.setVerbosity(params.isVerbose());

  {
    const double prob = axom::utilities::random_real(0., 1.);
    int localDomainCount = params.minDomainCount
      + int(0.5 + prob*(params.maxDomainCount-params.minDomainCount));
    object_mesh_wrapper.generateCircleMesh(circle,
                                           params.circlePoints,
                                           localDomainCount,
                                           params.randomSpacing);
  }

  SLIC_INFO_IF(params.isVerbose(),
               axom::fmt::format("Object mesh has {} points",
                                 object_mesh_wrapper.numPoints()));

  object_mesh_wrapper.saveMesh(params.objectFile);
  slic::flushStreams();

  //---------------------------------------------------------------------------
  // Load computational mesh and generate a particle mesh over its nodes
  // These will be used to query the closest points on the object mesh(es)
  //---------------------------------------------------------------------------
  QueryMeshWrapper query_mesh_wrapper(params.distanceFile,
                                      params.getDCMeshName(),
                                      params.meshFile);
  query_mesh_wrapper.printMeshInfo();

  const bool rankHasQueryPoints =
    axom::utilities::random_real(0., 1.) < (1. - params.percentEmptyRanks());

  // Copy mesh nodes into qpts array
  auto qPts = query_mesh_wrapper.getVertexPositions<PointArray>();
  const int nMeshPoints = qPts.size();
  const int nQueryPts = rankHasQueryPoints ? nMeshPoints : 0;

  SLIC_INFO_IF(
    params.isVerbose(),
    axom::fmt::format("Query mesh has {} points on rank {}", nQueryPts, my_rank));
  slic::flushStreams();

  //---------------------------------------------------------------------------
  // Initialize spatial index for querying points, and run query
  //---------------------------------------------------------------------------

  auto init_str =
    banner(axom::fmt::format("Initializing BVH tree over {} points",
                             params.circlePoints));

  auto query_str = banner(
    axom::fmt::format("Computing closest points for {} query points", nQueryPts));

  axom::utilities::Timer initTimer(false);
  axom::utilities::Timer queryTimer(false);

  // Convert blueprint representation from sidre to conduit
  conduit::Node object_mesh_node;
  if(object_mesh_wrapper.numPoints() > 0)
  {
    object_mesh_wrapper.getBlueprintGroup()->createNativeLayout(object_mesh_node);
  }

  // Put sidre data into Conduit query_mesh_node.
  /*
    TODO: Make query_mesh_node a multi-domain blueprint node.
    If rank has no query point, then no child domain node.
  */
  conduit::Node query_mesh_node;
  if(rankHasQueryPoints)
  {
    query_mesh_wrapper.getBlueprintGroup()->createNativeLayout(query_mesh_node);
  }

  // Create distributed closest point query object and set some parameters
  quest::DistributedClosestPoint query;
  query.setRuntimePolicy(params.policy);
  query.setMpiCommunicator(MPI_COMM_WORLD, true);
  query.setDimension(DIM);
  query.setVerbosity(params.isVerbose());
  query.setDistanceThreshold(params.distThreshold);
  query.setObjectMesh(object_mesh_node, object_mesh_wrapper.getCoordsetName());

  // Build the spatial index over the object on each rank
  SLIC_INFO(init_str);
  slic::flushStreams();
  initTimer.start();
  query.generateBVHTree();
  initTimer.stop();

  // Run the distributed closest point query over the nodes of the computational mesh
  SLIC_INFO(query_str);
  slic::flushStreams();
  queryTimer.start();
  query.computeClosestPoints(query_mesh_node,
                             query_mesh_wrapper.getCoordsetName());
  queryTimer.stop();

  auto getMinMax =
    [](double inVal, double& minVal, double& maxVal, double& sumVal) {
      MPI_Allreduce(&inVal, &minVal, 1, MPI_DOUBLE, MPI_MIN, MPI_COMM_WORLD);
      MPI_Allreduce(&inVal, &maxVal, 1, MPI_DOUBLE, MPI_MAX, MPI_COMM_WORLD);
      MPI_Allreduce(&inVal, &sumVal, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
    };

  // Output some timing stats
  {
    double minInit, maxInit, sumInit;
    getMinMax(initTimer.elapsedTimeInSec(), minInit, maxInit, sumInit);

    double minQuery, maxQuery, sumQuery;
    getMinMax(queryTimer.elapsedTimeInSec(), minQuery, maxQuery, sumQuery);

    SLIC_INFO(axom::fmt::format(
      "Initialization with policy {} took {{avg:{}, min:{}, max:{}}} seconds",
      params.policy,
      sumInit / num_ranks,
      minInit,
      maxInit));
    SLIC_INFO(axom::fmt::format(
      "Query with policy {} took {{avg:{}, min:{}, max:{}}} seconds",
      params.policy,
      sumQuery / num_ranks,
      minQuery,
      maxQuery));
  }
  slic::flushStreams();

  auto cpCoords =
    query_mesh_wrapper.getParticleMesh().getNodalVectorField<PointType>(
      "cp_coords");

  auto cpIndices =
    query_mesh_wrapper.getParticleMesh().getNodalScalarField<axom::IndexType>(
      "cp_index");

  if(params.isVerbose() && rankHasQueryPoints)
  {
    auto cpRank =
      query_mesh_wrapper.getParticleMesh().getNodalScalarField<axom::IndexType>(
        "cp_rank");

    SLIC_INFO(axom::fmt::format("Closest points ({}):", cpCoords.size()));
    for(auto i : IndexSet(cpCoords.size()))
    {
      SLIC_INFO(axom::fmt::format("\t{}: {{rank:{}, index:{}, position:{}}}",
                                  i,
                                  cpRank[i],
                                  cpIndices[i],
                                  cpCoords[i]));
    }
  }

  int errCount = 0;
  int localErrCount = 0;
  if(params.checkResults && rankHasQueryPoints)
  {
    localErrCount = query_mesh_wrapper.checkClosestPoints<DIM>(circle, params);
  }
  MPI_Allreduce(&localErrCount, &errCount, 1, MPI_INT, MPI_SUM, MPI_COMM_WORLD);

  //---------------------------------------------------------------------------
  // Transform closest points to distances and directions
  //---------------------------------------------------------------------------
  using primal::squared_distance;

  auto* distances = query_mesh_wrapper.getDC()->GetField("distance");
  auto* directions = query_mesh_wrapper.getDC()->GetField("direction");

  // Output some stats about the per-rank query points
  {
    double minPts, maxPts, sumPts;
    getMinMax(distances->Size(), minPts, maxPts, sumPts);
    SLIC_INFO(
      axom::fmt::format(" Query points: {{total:{}, min:{}, max:{}, avg:{}}}",
                        sumPts,
                        minPts,
                        maxPts,
                        sumPts / num_ranks));
    slic::flushStreams();
  }

  mfem::Array<int> dofs;
  PointType nowhere(std::numeric_limits<double>::signaling_NaN());
  const double nodist = std::numeric_limits<double>::signaling_NaN();
  for(auto idx : IndexSet(nMeshPoints))
  {
    const bool has_cp = rankHasQueryPoints && cpIndices[idx] >= 0;
    const auto& cp = has_cp ? cpCoords[idx] : nowhere;

    (*distances)(idx) = has_cp ? sqrt(squared_distance(qPts[idx], cp)) : nodist;

    directions->FESpace()->GetVertexVDofs(idx, dofs);
    directions->SetSubVector(dofs,
                             has_cp ? (cp - qPts[idx]).data() : nowhere.data());
  }

  //---------------------------------------------------------------------------
  // Cleanup, save mesh/fields and exit
  //---------------------------------------------------------------------------
  query_mesh_wrapper.saveMesh();

  finalizeLogger();
  MPI_Finalize();

  return errCount != 0;
}
