// Copyright (c) 2017-2024, Lawrence Livermore National Security, LLC and
// other Axom Project Developers. See the top-level LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#ifndef AXOM_ANNOTATION_MACROS_HPP_
#define AXOM_ANNOTATION_MACROS_HPP_

#include "axom/config.hpp"
#include "axom/core/utilities/Annotations.hpp"

// Note: Caliper integration into Axom is underway.
//       Axom's annotations will soon rely on caliper.

#include "axom/core/utilities/nvtx/interface.hpp"

/*!
 * \def AXOM_PERF_MARK_FUNCTION( name )
 * 
 * \brief The AXOM_PERF_MARK_FUNCTION is used to annotate a function.
 * 
 * \param [in] name a user-supplied name to annotate the function.
 * 
 * \note Typically, the AXOM_PERF_MARK_FUNCTION is placed in the beginning of
 *  the function to annotate.
 * 
 * 
 * \warning The AXOM_PERF_MARK_FUNCTION can only be called once within a given
 *  (function) scope.
 * 
 * 
 * Usage Example:
 * \code
 *   void foo( )
 *   {
 *     AXOM_PERF_MARK_FUNCTION( "foo" );
 *     ... 
 *   }
 * \endcode
 */
#if defined(AXOM_USE_ANNOTATIONS)
  #define AXOM_PERF_MARK_FUNCTION(__func_name__) \
    AXOM_NVTX_FUNCTION(__func_name__)
#else
  #define AXOM_PERF_MARK_FUNCTION(__func_name__)
#endif

/*!
 * \def AXOM_PERF_MARK_SECTION( name )
 *  
 * \brief The AXOM_PERF_MARK_SECTION macro is used to annotate sections of code.
 * 
 * \note In contrast to the AXOM_PERF_MARK_FUNCTION, the AXOM_PERF_MARK_SECTION
 *  macro is used to annotate sections of code at a much finer granularity
 *  within a given function and it may be use in conjunction with the 
 *  AXOM_PERF_MARK_FUNCTION macro.
 * 
 * \warning Variables declared within an AXOM_PERF_MARK_SECTION are only defined
 *  within the scope of the annotated section.
 * 
 * \warning The AXOM_PERF_MARK_SECTION macro may not be called in a nested
 *  fashion, i.e., within another AXOM_PERF_MARK_SECTION
 *
 * Usage Example:
 * \code
 *   void foo( )
 *   {
 *      AXOM_PERF_MARK_FUNCTION( "foo" );
 *      
 *      AXOM_PERF_MARK_SECTION( "kernel_A",
 *        axom::for_all( 0, N, AXOM_LAMBDA(axom::IndexType idx)
 *        { 
 *          ...
 *        } );
 *      );
 * 
 *      AXOM_PERF_MARK_SECTION( "kernel_B",
 *        axom::for_all( 0, N, AXOM_LAMBDA(axom::IndexType idx)
 *        {
 *          ...
 *        } );
 *      );
 * 
 *   }
 * \endcode
 * 
 */
#if defined(AXOM_USE_ANNOTATIONS)
  #define AXOM_PERF_MARK_SECTION(__name__, ...) \
    AXOM_NVTX_SECTION(__name__, __VA_ARGS__)
#else
  #define AXOM_PERF_MARK_SECTION(__name__, ...) \
    do                                          \
    {                                           \
      __VA_ARGS__                               \
    } while(false)
#endif

#ifdef AXOM_USE_CALIPER

  /*!
 * \def AXOM_ANNOTATE_BEGIN( name )
 * 
 * \brief This macro is used to mark the beginning of an annotated region
 * \note \a AXOM_ANNOTATE_BEGIN must be closed with a matching \a AXOM_ANNOTATE_END
 */
  #define AXOM_ANNOTATE_BEGIN(name) axom::utilities::annotations::begin(name)

  /*!
 * \def AXOM_ANNOTATE_END( name )
 * 
 * \brief This macro is used to mark the end of an annotated region
 * \note \a AXOM_ANNOTATE_END must close a matching \a AXOM_ANNOTATE_BEGIN
 */
  #define AXOM_ANNOTATE_END(name) axom::utilities::annotations::end(name)

  /*!
 * \def AXOM_ANNOTATE_SCOPE( name )
 * \brief This macro is used to annotate a region within an enclosing scope
 * and is automatically closed when its enclosing scope ends
 * 
 * \warning The \a AXOM_ANNOTATE_SCOPE can only be called once within a given scope.
 */
  #define AXOM_ANNOTATE_SCOPE(name)                        \
    cali::Annotation::Guard cali_autogenerated_guard_name( \
      cali::Annotation("region").begin(std::string(name).c_str()))

  /*!
 * \def AXOM_ANNOTATE_METADATA( name, value, category )
 * \brief This macro is used to add metadata to the run and is added to caliper output
 * in modes that generate an output file.
 * \see axom::utilities::annotations::declare_metadata
 */
  #define AXOM_ANNOTATE_METADATA(name, value, category) \
    axom::utilities::annotations::declare_metadata(name, value, category)

#else
  // clang-format off
  #define AXOM_ANNOTATE_BEGIN(name)                     do{} while(false)
  #define AXOM_ANNOTATE_END(name)                       do{} while(false)
  #define AXOM_ANNOTATE_SCOPE(name)                     do{} while(false)
  #define AXOM_ANNOTATE_METADATA(name, value, category) do{} while(false)
  // clang-format on
#endif

#endif
