#!/usr/bin/env bash

# Copyright (c) 2017-2021, Lawrence Livermore National Security, LLC and
# other Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

##-----------------------------------------------------------------------
## post-checkout hook to automatically update submodules. 
##
## This hook is executed after every `git checkout` or `git clone` 
## commands. It ensures that the submodules are up-to-date with
## respect to the current HEAD. 
##-----------------------------------------------------------------------
reset=$(tput sgr0)
bold=$(tput bold)

echo "$bold updating submodules...$reset"
git submodule update --recursive
echo "$bold[DONE]$reset"
