# -------------------------------------------------------------------------
# This file controls default concretization preferences for Spack.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/packages.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/packages.yaml
# -------------------------------------------------------------------------
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
# Spack may grab for mpi & we don't want to use them
  charm:
    buildable: false
  mpilander:
    buildable: false
# System level packages to not build
  autotools:
    buildable: false
    externals:
    - spec: autotools
      prefix: /usr/bin/
  bzip2:
    buildable: false
    externals:
    - spec: bzip2
      prefix: /usr/bin/
  gettext:
    buildable: false
    externals:
    - spec: gettext
      prefix: /usr/bin/
  m4:
    buildable: false
    externals:
    - spec: m4
      prefix: /usr/bin/
  pkg-config:
    buildable: false
    externals:
    - spec: pkg-config
      prefix: /usr/bin/
  tar:
    buildable: false
    externals:
    - spec: tar
      prefix: /usr/bin/
  graphviz:
    buildable: false
    externals:
    - spec: graphviz
      prefix: /usr/bin/
  raja:
    buildable: false
    externals:
    - spec: raja
      prefix: /usr/local/share/raja/cmake
# Globally lock in version of CMake
  cmake:
    version: [3.10.1]
# Globally lock version of third party libraries
  conduit:
    version: [0.5.1]
    variants: ~shared
  mfem:
    variants: ~mpi~metis~zlib
