# Copyright (c) 2017-2024, Lawrence Livermore National Security, LLC and
# Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

spack:
  config:
    install_tree:
      root: $spack/..
      projections:
        all: '{compiler.name}-{compiler.version}/{name}-{version}-{hash}'
    misc_cache: $spack/../misc_cache
    test_stage: $spack/../test_stage
    build_stage::
    - $spack/../build_stage

  # Regular TPLs do not need views
  view: false

  compilers::
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: elcapitan
      paths:
        cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
        cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
        f77: /usr/local/bin/gfortran
        fc: /usr/local/bin/gfortran
      spec: clang@7.3.0-apple
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: highsierra
      paths:
        cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
        cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
        f77: /usr/local/bin/gfortran
        fc: /usr/local/bin/gfortran
      spec: clang@9.0.0
  - compiler:
      environment: {}
      extra_rpaths: []
      flags: {}
      modules: []
      operating_system: mojave
      paths:
        cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
        cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
        f77: /usr/local/bin/gfortran
        fc: /usr/local/bin/gfortran
      spec: clang@10.0.0-apple

  packages::
    all:
      compiler: [gcc, intel, pgi, clang, xl, nag]
      providers:
        awk: [gawk]
        blas: [openblas]
        daal: [intel-daal]
        elf: [elfutils]
        golang: [gcc]
        ipp: [intel-ipp]
        java: [jdk]
        lapack: [openblas]
        mkl: [intel-mkl]
        mpe: [mpe2]
        mpi: [mpich, openmpi]
        opencl: [pocl]
        openfoam: [openfoam-com, openfoam-org, foam-extend]
        pil: [py-pillow]
        scalapack: [netlib-scalapack]
        szip: [libszip, libaec]
        tbb: [intel-tbb]
        jpeg: [libjpeg-turbo, libjpeg]
    # CUDA standard MacOS install
    cuda:
      buildable: false
      externals:
      - spec: cuda@8.0
        prefix: /Developer/NVIDIA/CUDA-8.0
    # System level packages to not build
    autotools:
      buildable: false
      externals:
      - spec: autotools
        prefix: /usr/bin/
    bzip2:
      buildable: false
      externals:
      - spec: bzip2
        prefix: /usr/bin/
    gettext:
      buildable: false
      externals:
      - spec: gettext
        prefix: /usr/bin/
    m4:
      buildable: false
      externals:
      - spec: m4
        prefix: /usr/bin/
    pkg-config:
      buildable: false
      externals:
      - spec: pkg-config
        prefix: /usr/bin/
    tar:
      buildable: false
      externals:
      - spec: tar
        prefix: /usr/bin/
    # Globally lock in version of CMake
    cmake:
      version: [3.9.6]

    # Globally lock version of third party libraries
    conduit:
      require: "@0.8.6~shared~test~examples~utilities"
    hdf5:
      variants: ~shared~mpi
    mfem:
      require: "@4.5~mpi~metis~zlib"
    raja:
      variants: ~shared~examples~exercises
    scr:
      version: [develop]
      variants: ~shared
    umpire:
      variants: ~shared~examples
