# Copyright (c) Lawrence Livermore National Security, LLC and other
# Axom Project Contributors. See top-level LICENSE and COPYRIGHT
# files for dates and other details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

import pysidre
import numpy as np
from conduit import Node

###############################################################################
# Tests from sidre_external.cpp
###############################################################################

def test_create_external_view():
	ds = pysidre.DataStore()
	root = ds.getRoot()

	length = 11
	ndims = 1
	shape = np.array([length])

	idata = np.array(range(length))
	print(f"PYTHON SIDE: idata type is {type(idata[0])}")
	print(f"PYTHON SIDE: idata is {idata}")

	for i in range(8):
		view = None
		match i:
			case 0:
				view = root.createView("data0", pysidre.TypeID.INT64_ID, length, idata)
			case 1:
				view = root.createView("data1", pysidre.TypeID.INT64_ID, length).setExternalData(idata)
			case 2:
				view = root.createView("data2").setExternalData(pysidre.TypeID.INT64_ID, length, idata)
			case 3:
				view = root.createView("data3", idata).apply(pysidre.TypeID.INT64_ID, length)
			case 4:
				view = root.createViewWithShape("data4", pysidre.TypeID.INT64_ID, ndims, shape, idata)
			case 5:
				view = root.createViewWithShape("data5", pysidre.TypeID.INT64_ID, ndims, shape).setExternalData(idata)
			case 6:
				view = root.createView("data6").setExternalData(pysidre.TypeID.INT64_ID, ndims, shape, idata)
			case 7:
				view = root.createView("data7", idata).apply(pysidre.TypeID.INT64_ID, ndims, shape)

		assert view is not None
		assert root.getNumViews() == i + 1

		assert view.isDescribed()
		assert view.isAllocated()
		assert view.isApplied()

		assert view.isExternal()
		assert not view.isOpaque()

		assert view.getTypeID() == pysidre.TypeID.INT64_ID
		assert view.getNumElements() == length

		view.print()

		idata_chk = view.getDataArray()
		assert np.array_equal(idata_chk, idata)

		for ii in range(length):
			assert idata_chk[ii] == idata[ii]


def test_verify_external_layout():
	ds = pysidre.DataStore()
	root = ds.getRoot()

	SZ = 11
	extData = np.zeros(SZ, dtype=np.int64)

	print("""Tests that the hierarchy generated by Group::createExternalLayout()
	consists only of groups and views
	associated with external pointers (described or undescribed).""")

	# Create some internal views
	root.createViewAndAllocate("int/desc/bufferview", pysidre.TypeID.INT64_ID, SZ)
	root.createViewScalar("int/scalar/scalarview", SZ)
	root.createViewString("int/string/stringview", "A string")

	# Sanity check on internal views
	assert not root.getView("int/desc/bufferview").isExternal()
	assert root.getView("int/desc/bufferview").isDescribed()
	assert not root.getView("int/scalar/scalarview").isExternal()
	assert root.getView("int/scalar/scalarview").isDescribed()
	assert not root.getView("int/string/stringview").isExternal()
	assert root.getView("int/string/stringview").isDescribed()

	# Check that the generated external layout is empty
	emptyNode = Node()
	root.createExternalLayout(emptyNode)

	print("External node's json before adding external data (should be empty):\n\t", emptyNode.to_json())

	assert emptyNode.number_of_children() == 0

	# Create some external views
	root.createView("ext/desc/external_desc", pysidre.TypeID.INT64_ID, SZ, extData)
	root.createView("ext/undesc/external_opaque").setExternalData(extData)

	# Sanity check on the external views
	assert root.getView("ext/desc/external_desc").isExternal()
	assert root.getView("ext/desc/external_desc").isDescribed()

	assert root.getView("ext/undesc/external_opaque").isExternal()
	assert not root.getView("ext/undesc/external_opaque").isDescribed()

	# Initialize the data so we can test it later
	bufData = root.getView("int/desc/bufferview").getDataArray()
	for i in range(SZ):
		extData[i] = i
		bufData[i] = 100 + i

	# Check that the generated external layout matches expectation
	# Copy the external layout into a conduit node and test the layout
	node = Node()
	root.createExternalLayout(node)

	print("External node's json:\n\t", node.to_json())

	assert node.number_of_children() == 1
	assert node.has_path("ext")
	assert node["ext"].number_of_children() == 2

	# Described external views are present and we can access the data
	assert node.has_path("ext/desc")
	assert node.has_path("ext/desc/external_desc")
	extLayoutData = node["ext/desc/external_desc"]
	for i in range(SZ):
		assert extData[i] == extLayoutData[i]

	# Opaque views are not present, but their containing groups are present
	assert node.has_path("ext/undesc")
	assert not node.has_path("ext/undesc/external_opaque")

	# Buffer and scalar views are not present in the external layout
	assert not node.has_path("int")


def test_save_load_external_view():
	if not pysidre.AXOM_USE_HDF5:
		print("pysidre.Group.loadExternalData() is only implemented for the 'sidre_hdf5' protocol")
		return

	ds = pysidre.DataStore()
	root = ds.getRoot()

	length = 11

	idata = np.array([ii for ii in range(length)], dtype=np.int64)
	ddata = np.array([ii * 2.0 for ii in range(length)], dtype=np.float64)

	# Create views with external data
	root.createView("idata", idata).apply(pysidre.TypeID.INT64_ID, length)
	root.createView("ddata", ddata).apply(pysidre.TypeID.FLOAT64_ID, length)
	assert root.getNumViews() == 2

	root.save("sidre_external_save_load_external_view", "sidre_hdf5")

	ds2 = pysidre.DataStore()
	load_group = ds2.getRoot()

	# Load from file, the Views with external data will be described but
	# have no pointer to data
	load_group.load("sidre_external_save_load_external_view")

	# Verify load_group has external Views named "idata" and "ddata"
	assert load_group.hasView("idata")
	assert load_group.hasView("ddata")
	load_idata = load_group.getView("idata")
	load_ddata = load_group.getView("ddata")
	assert load_idata.isExternal()
	assert load_ddata.isExternal()
	assert load_idata.getNumElements() == length
	assert load_ddata.getNumElements() == length
	assert load_idata.getTypeID() == pysidre.TypeID.INT64_ID
	assert load_ddata.getTypeID() == pysidre.TypeID.FLOAT64_ID

	# Create arrays that will serve as locations for external data
	new_idata = np.zeros(length, dtype=np.int64)
	new_ddata = np.zeros(length, dtype=np.float64)

	# Set the new arrays' pointers into the Views
	load_idata.setExternalData(new_idata)
	load_ddata.setExternalData(new_ddata)

	# Load external data; values located in the file will be loaded into
	# the storage identified by the external pointers
	load_group.loadExternalData("sidre_external_save_load_external_view")

	# The pointer retrieved from each View is the same address as the new
	# arrays
	idata_chk = load_group.getView("idata").getDataArray()
	assert np.array_equal(idata_chk, new_idata)

	# idata_chk has been loaded with the values from the file, which must
	# be the same as the original idata array that was saved
	for ii in range(length):
		assert idata_chk[ii] == idata[ii]

	ddata_chk = load_group.getView("ddata").getDataArray()
	assert np.array_equal(ddata_chk, new_ddata)
	for ii in range(length):
		assert ddata_chk[ii] == ddata[ii]



###############################################################################
# Tests from sidre_external_F.f
###############################################################################

# External numpy array via python
# Register with datastore then
# Query metadata using datastore API.
def test_external_int():
	ds = pysidre.DataStore()
	root = ds.getRoot()

	iarray = np.array(range(1,11))

	view = root.createView("iarray", iarray)
	view.apply(pysidre.TypeID.INT64_ID, 10)

	assert view.isExternal() == True
	assert view.getTypeID() == pysidre.TypeID.INT64_ID
	assert view.getNumElements() == np.size(iarray)
	assert view.getNumDimensions() == 1

	extents = np.zeros(7)
	rank,extents = view.getShape(7, extents)
	assert rank == 1
	assert extents[0] == np.size(iarray)

	ipointer = view.getDataArray()
	assert np.array_equal(ipointer, iarray)


def test_external_int_3d():
	ds = pysidre.DataStore()
	root = ds.getRoot()

	# create 3D numpy array
	iarray = np.empty((2, 3, 4), dtype=int)

	for i in range(2):
		for j in range(3):
			for k in range(4):
				iarray[i, j, k] = (i+1)*100 + (j+1)*10 + (k+1)
	view = root.createView("iarray", iarray)
	view.apply(pysidre.TypeID.INT64_ID, 3, np.array([2,3,4]))

	assert view.isExternal() == True
	assert view.getTypeID() == pysidre.TypeID.INT64_ID
	assert view.getNumElements() == np.size(iarray)
	assert view.getNumDimensions() == 3

	extents = np.zeros(7)
	rank,extents = view.getShape(7, extents)
	assert rank == 3
	assert extents[0] == iarray.shape[0]
	assert extents[1] == iarray.shape[1]
	assert extents[2] == iarray.shape[2]

	ipointer = view.getDataArray()
	assert np.array_equal(ipointer, iarray)


# check other types
def test_external_float():
	ds = pysidre.DataStore()
	root = ds.getRoot()

	darray = np.array([(i + 0.5) for i in range(1,11)])
	view = root.createView("darray", darray)
	view.apply(pysidre.TypeID.FLOAT64_ID, 10)

	assert view.getTypeID() == pysidre.TypeID.FLOAT64_ID
	assert view.getNumElements() == np.size(darray)

	dpointer = view.getDataArray()
	assert np.array_equal(dpointer, darray)


# Datastore owns a multi-dimension array.
def test_datastore_int_3d():
	ds = pysidre.DataStore()
	root = ds.getRoot()
	extents_in = [2,3,4]

	view = root.createViewWithShapeAndAllocate("iarray", pysidre.TypeID.INT32_ID, 3, extents_in)

	ipointer = view.getDataArray()

	assert view.getTypeID() == pysidre.TypeID.INT32_ID
	assert view.getNumElements() == np.size(ipointer)
	assert view.getNumDimensions() == 3
	assert view.getNumDimensions() == ipointer.ndim

	extents = np.zeros(7)
	rank,extents = view.getShape(7, extents)
	assert rank == 3
	assert extents[0] == ipointer.shape[0]
	assert extents[1] == ipointer.shape[1]
	assert extents[2] == ipointer.shape[2]

	# Reshape as 1D using shape
	extents_in[0] = np.size(ipointer)
	view.apply(pysidre.TypeID.INT32_ID, 1, np.array([extents_in[0]]))
	assert view.getNumElements() == np.size(ipointer)

	# Reshape as 1D using length
	view.apply(pysidre.TypeID.INT32_ID, extents_in[0])
	assert view.getNumElements() == np.size(ipointer)
