#!/bin/sh
"exec" "python" "-u" "-B" "$0" "$@"

import os
import sys


def printUsage():
    print "Usage: runLumberjackTest <sample input> <# of mpi nodes>\n"


def main():
    if len(sys.argv) != 3:
        print "Error: Wrong amount of command line options"
        printUsage()
        return False
    if not os.path.exists(sys.argv[1]):
        print "Error: Sample input does not exist"
        printUsage()
        return False
    if os.path.isdir(sys.argv[1]):
        print "Error: Sample input is a directory"
        printUsage()
        return False
    fileName = sys.argv[1]
    fileNameExpanded = fileName + "Expanded"
    numMPINodes = int(sys.argv[2])

    with open(fileName, "r") as f:
        lines = f.readlines()

    with open(fileNameExpanded, "w") as f:
        for currLine in lines:
            for x in range(0, numMPINodes):
                if not currLine.endswith("\n") and not x == numMPINodes-1:
                    f.write(currLine + "\n")
                else:
                    f.write(currLine)
    return True

if __name__ == "__main__":
    if not main():
        sys.exit(1)
    sys.exit(0)
