// utilQUEST.cpp
// This file is generated by Shroud 0.14.0. Do not edit.
//
// Copyright (c) Lawrence Livermore National Security, LLC and other
// Axom Project Contributors. See top-level LICENSE and COPYRIGHT
// files for dates and other details.
//
// SPDX-License-Identifier: (BSD-3-Clause)

#include "typesQUEST.h"

#ifdef __cplusplus
extern "C" {
#endif

// Release library allocated memory.
void QUEST_SHROUD_memory_destructor(QUEST_SHROUD_capsule_data *cap)
{
  cap->addr = nullptr;
  cap->idtor = 0;  // avoid deleting again
  cap->cmemflags = cap->cmemflags & ~SWIG_MEM_OWN;
}

#ifdef __cplusplus
}
#endif
