# This is a basic workflow that is manually triggered

name: Manual test for Axom's TPLs on Windows

# Controls when the action will run. 
# This workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will check out the repo and invoke uberenv to build and test our TPLs
  run_uberenv:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repo w/ submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: List path and files
      run: ls
    - name: Temp -- checkout update-mfem branch
      run: |
        git checkout feature/kweiss/update-mfem
        git status
    - name: Run uberenv (x64-windows)
      run: python3 ./scripts/uberenv/uberenv.py --triplet "x64-windows"
    - name: Copy host-config
      run: Copy-Item -Path ".\uberenv_libs\*.cmake" -Destination "hc.cmake"
    - name: Configure axom
      run: |
        python3 config-build.py -bp build-axom -ip install-axom -hc hc.cmake --msvc 201964
    - name: Build axom debug
      run: |
        cd build-axom
        ls
        cmake --build . --config Debug
    - name: Test axom debug
      run: |
        cd build-axom
        ls
        ctest -C Debug
    - name: Build axom release
      run: |
        cd build-axom
        ls
        cmake --build . --config Release
    - name: Test axom release
      run: |
        cd build-axom
        ls
        ctest -C Release
